### ISSUE TITLE
执行Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo的./run.sh遇到问题

### ISSUE THREAD

**Issue by feiwei93** [PaddlePaddle/Paddle-Lite-Demo#102]
如题，我在执行PaddleLite-armlinux-demo/object_detection_demo的./run.sh armv8这一步出现问题，如下：

/home/nvidia/Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc: In function ‘std::vector<std::__cxx11::basic_string<char> > load_labels(const string&)’:
/home/nvidia/Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc:52:17: error: aggregate ‘std::ifstream file’ has incomplete type and cannot be defined
   std::ifstream file;
                 ^~~~
/home/nvidia/Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc: In function ‘cv::Mat process(cv::Mat&, std::vector<std::__cxx11::basic_string<char> >&, std::shared_ptr<paddle::lite_api::PaddlePredictor>&)’:
/home/nvidia/Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc:220:41: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<RESULT>::size_type {aka long unsigned int}’ [-Wformat=]
   printf("results: %d\n", results.size());
                           ~~~~~~~~~~~~~~^
CMakeFiles/object_detection_demo.dir/build.make:62: recipe for target 'CMakeFiles/object_detection_demo.dir/object_detection_demo.cc.o' failed
make[2]: *** [CMakeFiles/object_detection_demo.dir/object_detection_demo.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/object_detection_demo.dir/all' failed
make[1]: *** [CMakeFiles/object_detection_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
./run.sh: line 19: ./object_detection_demo: No such file or directory

**Comment by command-z-z** [comment]
问题解决了吗

**Comment by sushidelivery** [comment]
same issue ;( anybody solved?
