### ISSUE TITLE
libavcodec.so.58: undefined reference to `bcm_host_is_fkms_active'

### ISSUE THREAD

**Issue by aawujie** [PaddlePaddle/Paddle-Lite-Demo#107]
....
[100%] Linking CXX executable image_classification_demo
/usr/bin/ld: //usr/lib/arm-linux-gnueabihf/libavcodec.so.58: undefined reference to `bcm_host_is_fkms_active'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/image_classification_demo.dir/build.make:136：image_classification_demo] 错误 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/image_classification_demo.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
./run.sh:行19: ./image_classification_demo: 没有那个文件或目录

这个怎么办，树莓派环境

**Comment by aawujie** [comment]
运行 Paddle-Lite-Demo/PaddleLite-armlinux-demo/image_classification_demo/run.sh 出现的

**Comment by TangYuan-Liu** [comment]
你好，可以通过更新kernel以及firmware解决这个问题，详细请参考链接：https://github.com/raspberrypi/firmware/issues/1319
