### ISSUE TITLE
在Ubuntu16.04的环境下，编译Paddle-Lite-Demo报错。

### ISSUE THREAD

**Issue by YangLiu0427** [PaddlePaddle/Paddle-Lite-Demo#110]
命令：./run.sh armv8
错误：
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TARGET ARCH ABI: armv8
-- PADDLE LITE DIR: ../Paddle-Lite
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Found OpenMP  4.0
-- OpenMP C flags:  -fopenmp
-- OpenMP CXX flags:  -fopenmp
-- OpenMP OpenMP_CXX_LIB_NAMES:  gomp;pthread
-- OpenMP OpenMP_CXX_LIBRARIES:  /usr/lib/gcc-cross/aarch64-linux-gnu/5/libgomp.so;/usr/aarch64-linux-gnu/lib/libpthread.so
-- Found OpenCV: /usr/local (found version "3.4.1") 
-- OpenCV library status:
--     version: 3.4.1
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz
--     include path: /usr/local/include;/usr/local/include/opencv
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Desktop/face/Paddle-Lite-Demo/PaddleLite-armlinux-demo/image_classification_demo/build
Scanning dependencies of target image_classification_demo
[ 50%] Building CXX object CMakeFiles/image_classification_demo.dir/image_classification_demo.cc.o
[100%] Linking CXX executable image_classification_demo
/usr/local/lib/libopencv_dnn.so.3.4.1: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/image_classification_demo.dir/build.make:101: recipe for target 'image_classification_demo' failed
make[2]: *** [image_classification_demo] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/image_classification_demo.dir/all' failed
make[1]: *** [CMakeFiles/image_classification_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
./run.sh: line 19: ./image_classification_demo: No such file or directory

似乎是与OpenCV有关系，我分别试了OpenCV3.4.1和OpenCV4.3.0，但是都报一样的错误，大神请帮忙看看是什么原因，十分感激。

**Comment by YangLiu0427** [comment]
你好，请问在Ubuntu16.04的虚拟机下，编译paddle-lite-demo，对OpenCV的版本有要求吗？

**Comment by YangLiu0427** [comment]
您好，换成OpenCV=3.2.0，有报错如下：
[ 50%] Building CXX object CMakeFiles/image_classification_demo.dir/image_classification_demo.cc.o
[100%] Linking CXX executable image_classification_demo
/usr/local/lib/libopencv_shape.so.3.2.0: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/image_classification_demo.dir/build.make💯 recipe for target 'image_classification_demo' failed
make[2]: *** [image_classification_demo] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/image_classification_demo.dir/all' failed
make[1]: *** [CMakeFiles/image_classification_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
./run.sh: line 19: ./image_classification_demo: No such file or directory

查了很久，但是还是不知道原因，请帮忙看看，谢谢。

**Comment by k-user** [comment]
@YangLiu0427 老哥请问你这个问题解决了么，我也遇到了
