### ISSUE TITLE
Andorid yolo_detection_demo编译出错

### ISSUE THREAD

**Issue by wjhtinger** [PaddlePaddle/Paddle-Lite-Demo#115]
CMake Error at E:\code\AI\Paddle-Lite-Demo\PaddleLite-android-demo\yolo_detection_demo\app\src\main\cpp\CMakeLists.txt:17 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by cha0cha0** [comment]
demo在编译的时候回去拉取对应的依赖，正常情况下依赖拉取成功的话，在app目录下应该会有一个OpenCV的文件夹。看起来像是依赖拉取失败导致的

**Comment by hch-baobei** [comment]
我的目录下是有OpenCV的文件夹，依旧显示这个错误应该怎么办？ 很抱歉在这么久远的issue上问问题。
