### ISSUE TITLE
android object_detection_demo编译问题

### ISSUE THREAD

**Issue by QinZiwen** [PaddlePaddle/Paddle-Lite-Demo#116]
Build file 'Paddle-Lite-Demo/PaddleLite-android-demo/object_detection_demo/app/build.gradle' line: 53
代码如下：
```
copy {
    from tarTree("cache/${cacheName}.tar.gz")
    into "cache/${cacheName}"
}
```
Execution failed for task ':app:downloadAndExtractPaddleLiteLibs'.
> Unable to expand TAR 'Paddle-Lite-Demo/PaddleLite-android-demo/object_detection_demo/app/cache/7cmqbf01pue49s5cq5e7hme5s8.tar.gz'
    The tar might be corrupted or it is compressed in an unexpected way.
    By default the tar tree tries to guess the compression based on the file extension.
    If you need to specify the compression explicitly please refer to the DSL reference.

非常感谢

**Comment by cha0cha0** [comment]
在编译之前，把Paddle-Lite-Demo/PaddleLite-android-demo/object_detection_demo/app/cache/目录下的文件夹全部删除，只保留tar.gz文件，然后重新编译

**Comment by QinZiwen** [comment]
好的，非常感谢！
