### ISSUE TITLE
使用ocr_attention训练出来的结果发生崩溃

### ISSUE THREAD

**Issue by xiaolvtaomi** [PaddlePaddle/Paddle-Lite-Demo#12]
目的：使用ocr_attention训练出来的预测模型在android手机上运行
操作步骤：
1，将[预测模型](https://github.com/xiaolvtaomi/xiaolvtaomi.github.io/tree/master/attention)放在/assets/image_classification/models/test_model_ocr 目录下
2，将[测试图片](https://github.com/xiaolvtaomi/xiaolvtaomi.github.io/blob/master/img/000.jpg)放在/assets/image_classification/images/000.jpg
3，修改strings.xml 
` xml

    <string name="ICS_MODEL_PATH_DEFAULT">image_classification/labels/test_model_ocr</string>
    <string name="ICS_LABEL_PATH_DEFAULT">image_classification/labels/synset_words.txt</string>

    <string name="ICS_IMAGE_PATH_DEFAULT">image_classification/images/000.jpg</string>

    <string name="ICS_INPUT_SHAPE_DEFAULT">1,3,100,380</string>
`
4，修改了ImgClassifyPredictor的输出读取。

然后debug的时候会报错，错误节点发生在Predictor.java的runModel()方法中
`
public boolean runModel() {
    ...
    paddlePredictors.get(whichDevice).run();  // 报错
    ...
}
`

错误截图如下：
![image](https://user-images.githubusercontent.com/2050654/64397486-02aadc80-d094-11e9-8622-e826e38e6c4a.png)

**Comment by DannyIsFunny** [comment]
您好，我们在wiki中的“c++实例”中添加了"[CxxConfig案例: OCR_model的运行](https://github.com/PaddlePaddle/Paddle-Lite/wiki/cpp_demo)",    可以参考这个案例实现ocr attention。  
一般出现的问题有：
（1）OCR 三个输入的size不同，需要检查三个输入是否与自己的模型定义对齐
（2）需要输入pbtype的OCR model
（3）当前对于OCR model的saveoptimizemodel方法有一些问题，我们正在抓紧修复

**Comment by xiaolvtaomi** [comment]
![image](https://user-images.githubusercontent.com/2050654/64600051-0d93a300-d3ed-11e9-9ef6-992a0a1ed466.png)

是如图的方式修改
