### ISSUE TITLE
iOS detection_demo 替换基于YOLOV3-MobileNetV3的目标检测模型后crash

### ISSUE THREAD

**Issue by wanjj8023** [PaddlePaddle/Paddle-Lite-Demo#126]
1. clone demo到本地  sh执行更新  替换配置后 真机运行OK
2. 替换基于YOLOV3-MobileNetV3的目标检测模型到demo中
3. 下载对应导出模型的版本 2.8  [https://paddle-lite.readthedocs.io/zh/latest/quick_start/release_lib.html](url)
4. 更新demo中的预测库到2.8
运行crash 如下图
<img width="734" alt="截屏2021-04-22 上午11 39 53" src="https://user-images.githubusercontent.com/3202112/115652259-80058c80-a35f-11eb-8ea4-44d7b73b277a.png">

**Comment by wanjj8023** [comment]
模型输入问题

**Comment by SongYanLingyyt** [comment]
你好，请问这个问题怎么解决的，模型输入如何调整的啊
