### ISSUE TITLE
paddle X 训练的模型，用opt转成.nb，在树莓派上提示格式不对

### ISSUE THREAD

**Issue by guoxixiao** [PaddlePaddle/Paddle-Lite-Demo#133]
arning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:v2.9
      version of current Paddle-Lite:d42fd22
[I  5/26  8:27: 7.785 ...ddle-Lite/lite/kernels/arm/conv_direct.h:207 PrepareForRun] param.filter: 
[F  5/26  8:27:11.747 .../lite/kernels/host/elementwise_op_func.h:339 Update] Wrong broadcast type

**Comment by sdjxmikill** [comment]
opt和paddlelite版本要求一致，我也遇到了同样的问题。 https://github.com/PaddlePaddle/Paddle-Lite-Demo/issues/212
