### ISSUE TITLE
paddlelite文档有错误

### ISSUE THREAD

**Issue by Dilemma111** [PaddlePaddle/Paddle-Lite-Demo#134]
链接（https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_env.html）在该页面配置编译环境中：本地编译ARM Linux（直接在RK3399或树莓派上编译）的第二条命令apt-get install -y --no-install-recomends 应该为apt-get install -y --no-install-recommends 少了一个m 请及时改正 避免踩坑（本人已踩坑哈哈）

**Comment by hong19860320** [comment]
不好意思，回复晚了，谢谢你~
