### ISSUE TITLE
Android图像预处理很慢怎么优化？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle-Lite-Demo#135]
在Android中使用以下代码做预处理，需要时间35ms，而推理的时间只需要17ms，预处理时间都比预测时间要长了，有什么优化方法吗？

https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/25bf50a24c3e04b81fae2736e556a898f6173e72/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor.java#L187-L236

**Comment by yeyupiaoling** [comment]
我这样做速度超快。
```java
    public static float[] normalize(Mat mat, float[] mean, float[] std) {
        mat.convertTo(mat, CvType.CV_32FC3);
        Mat result = new Mat(mat.rows(), mat.cols(), CvType.CV_32FC3);
        // 执行归一化
        Core.subtract(mat, new Scalar(mean[0], mean[1], mean[2]), result);
        Core.divide(result, new Scalar(std[0], std[1], std[2]), result);
        // 按照bbb...ggg...rrr将数据提取到数组中
        float[] b = new float[(int) result.total()];
        float[] g = new float[(int) result.total()];
        float[] r = new float[(int) result.total()];
        List<Mat> matList = new ArrayList<>();
        Core.split(result, matList);
        matList.get(0).get(0, 0, b);
        matList.get(1).get(0, 0, g);
        matList.get(2).get(0, 0, r);
        float[] data = new float[(int) result.total() * 3];
        System.arraycopy(b, 0, data, 0, b.length);
        System.arraycopy(g, 0, data, b.length, g.length);
        System.arraycopy(r, 0, data, b.length + g.length, r.length);
        return data;
    }
```

**Comment by summer0906** [comment]
> 我这样做速度超快。
> 
> ```java
>     public static float[] normalize(Mat mat, float[] mean, float[] std) {
>         mat.convertTo(mat, CvType.CV_32FC3);
>         Mat result = new Mat(mat.rows(), mat.cols(), CvType.CV_32FC3);
>         // 执行归一化
>         Core.subtract(mat, new Scalar(mean[0], mean[1], mean[2]), result);
>         Core.divide(result, new Scalar(std[0], std[1], std[2]), result);
>         // 按照bbb...ggg...rrr将数据提取到数组中
>         float[] b = new float[(int) result.total()];
>         float[] g = new float[(int) result.total()];
>         float[] r = new float[(int) result.total()];
>         List<Mat> matList = new ArrayList<>();
>         Core.split(result, matList);
>         matList.get(0).get(0, 0, b);
>         matList.get(1).get(0, 0, g);
>         matList.get(2).get(0, 0, r);
>         float[] data = new float[(int) result.total() * 3];
>         System.arraycopy(b, 0, data, 0, b.length);
>         System.arraycopy(g, 0, data, b.length, g.length);
>         System.arraycopy(r, 0, data, b.length + g.length, r.length);
>         return data;
>     }
> ```

这样是需要完整引入openCV库是吗？

**Comment by yeyupiaoling** [comment]
@summer0906 是的哦
