### ISSUE TITLE
安卓端怎么使用GPU

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle-Lite-Demo#141]
请问在安卓里面怎么使用opencl，npu，或者opengl，bulkan等
看到demo默认是cpu的

**Comment by hong19860320** [comment]
需要编译带opencl的lite库，然后用opt工具在转模型的时候设置为arm,opencl，然后替换demo中的lite库、头文件和nb模型就行了

**Comment by shiyuxin1999S** [comment]
> 需要编译带opencl的lite库，然后用opt工具在转模型的时候设置为arm,opencl，然后替换demo中的lite库、头文件和nb模型就行了

请问转换模型的时候--valid_targets=opencl,arm --enable_fp16=true报错[F  6/13 20:19:57.734 /island/Paddle-Lite/lite/core/kernel.cc GetInputDeclType:34] Check failed: type: no type registered for kernel [conv2d] input argument [SecondInput] with key conv2d/def
已放弃 (核心已转储)
如果是--valid_targets=opencl,arm导出的模型会让软件闪退
如果--valid_targets=arm --enable_fp16=true，才不会报错，但是好像没用到opencl，请问您知道哪里有问题吗

**Comment by zhubinsheng** [comment]
> 需要编译带opencl的lite库，然后用opt工具在转模型的时候设置为arm,opencl，然后替换demo中的lite库、头文件和nb模型就行了

听起来感觉很简单，实际操作会不会要踩坑花很久
