### ISSUE TITLE
paddlelite在notebook上运行，代码执行器直接重启

### ISSUE THREAD

**Issue by peng-peng0913** [PaddlePaddle/Paddle-Lite-Demo#142]
日志报错

WARNING: Logging before InitGoogleLogging() is written to STDERR
E0711 21:43:24.758523 99 conv_op.cc:33] in_dims.size() == 4 || in_dims.size() == 5 test error!
F0711 21:43:24.758589 99 program.cc:470] Check failed: op_->CheckShape()
*** Check failure stack trace: ***

**Comment by hong19860320** [comment]
这个是什么demo执行的结果啊？是andriod吗？
