### ISSUE TITLE
paddlite库2_10_rc版本有问题

### ISSUE THREAD

**Issue by Zuile** [PaddlePaddle/Paddle-Lite-Demo#159]
新的paddlelite库2_10_rc版本在单线程模式下预测性能不如之前的2_9_1版本，而且线程数越高性能反倒还越差了，2_9_1版本没有这个问题，但是2_9_1版本跑yolo目标检测模型会报错

**Comment by Zuile** [comment]
重新测了一下，发现只有人脸检测的Ultra-Light-Fast-Generic-Face-Detector这个模型有这个问题，其他模型还是正常的

**Comment by sdjxmikill** [comment]
您好能否帮我解答一下这个问题，https://github.com/PaddlePaddle/Paddle-Lite-Demo/issues/212
