### ISSUE TITLE
例子只用了一个线程，跑起来相当慢

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle-Lite-Demo#17]
在[Predictor.java](https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/app/src/main/java/com/baidu/paddle/lite/demo/Predictor.java)中[loadModel](        https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/907c9603fdb64173aff8f92e63e994040f260408/PaddleLite-android-demo/app/src/main/java/com/baidu/paddle/lite/demo/Predictor.java#L47)函数里的
```
MobileConfig config = new MobileConfig();
config.setModelDir(realPath);
```
后加上开启多线程预测
```
config.setThreads(4);
```

**Comment by hong19860320** [comment]
是的，默认是单线程的，你可以按照需要设置成多线程。

**Comment by imistyrain** [comment]
这东西对于你们来说很简单就一句代码的事，可是那些刚开始弄的呢？跑半天发现很慢，就不用了。
能从用户角度考虑下吗

**Comment by hong19860320** [comment]
实在很抱歉，由于之前大部分业务要求预测库使用CPU资源时只允许单线程，所以采用默认单线程的，后面我们会在代码更新时会增加相关代码哦。

**Comment by hong19860320** [comment]
最新代码已经加了线程数量设置了

**Comment by imistyrain** [comment]
在readme里加个说明吧，怎么切换到4线程，感觉入口隐藏的很深，得操作好几步才行；而且使用了sharedPreferences，即使在代码里把线程设成4也不行。
