### ISSUE TITLE
目标检测例程都是基于ARM CPU加速的，怎么移植到X86 CPU上呢？

### ISSUE THREAD

**Issue by StephensonDing** [PaddlePaddle/Paddle-Lite-Demo#179]
可以给个例子看看吗？
![无标题](https://user-images.githubusercontent.com/71481524/151157817-93785d94-d947-46f6-8bb2-35228d71b467.png)

**Comment by chenjiaoAngel** [comment]
X86 CPU demo 可以参考：https://github.com/PaddlePaddle/Paddle-Lite/tree/develop/lite/demo/cxx/x86_mobilenetv1_light_demo

**Comment by StephensonDing** [comment]
> 

我是指X86 CPU图像目标检测的demo，上面链接中给的参考没有图片预处理的内容

**Comment by chenjiaoAngel** [comment]
这个有预处理：https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/cxx/mobile_classify/mobile_classify.cc#L110
neon_mean_scale 实现：
// 纯C版 dout_c0- 0 通道， dout_c1-1 通道， dout_c2 - 2通道
// 输入是NHWC 输出 NCHW
for (int i = 0; i < size; i++) {
    *(dout_c0++) = (*(din++) - mean[0]) / scale[0];
    *(dout_c1++) = (*(din++) - mean[1]) / scale[1];
    *(dout_c2++) = (*(din++) - mean[2]) / scale[2];
  }

**Comment by StephensonDing** [comment]
> 这个有预处理：https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/cxx/mobile_classify/mobile_classify.cc#L110 neon_mean_scale 实现： // 纯C版 dout_c0- 0 通道， dout_c1-1 通道， dout_c2 - 2通道 // 输入是NHWC 输出 NCHW for (int i = 0; i < size; i++) { _(dout_c0++) = (_(din++) - mean[0]) / scale[0]; _(dout_c1++) = (_(din++) - mean[1]) / scale[1]; _(dout_c2++) = (_(din++) - mean[2]) / scale[2]; }

您好，上面给的预处理使用的是ARM CPU的加速库neon，所以其中用到了“float32x4_t”这样的数据类型，我想请问的是，有没有X86 CPU上的加速实现啊？或者有其他能够在X86 CPU上运行的目标检测也行啊。

**Comment by chenjiaoAngel** [comment]
直接把neon 实现的部分内容注释，直接用如下C语言实现就行：

**Comment by chenjiaoAngel** [comment]
// 纯C版 dout_c0- 0 通道， dout_c1-1 通道， dout_c2 - 2通道
// 输入是NHWC 输出 NCHW
for (int i = 0; i < size; i++) {
(dout_c0++) = ((din++) - mean[0]) / scale[0];
(dout_c1++) = ((din++) - mean[1]) / scale[1];
(dout_c2++) = ((din++) - mean[2]) / scale[2];
}

**Comment by soham24** [comment]
@chenjiaoAngel I didnt find neaon_mean_scale_imp without neon. 
for comipiling on x86 
can you help me here?
Need to have these 2 methods without neon 
`
void NHWC3ToNC3HW(const float *din, float *dout, int size,
                  const std::vector<float> mean,
                  const std::vector<float> scale) {
  if (mean.size() != 3 || scale.size() != 3) {
    printf("[ERROR] mean or scale size must equal to 3\n");
    return;
  }
  float32x4_t vmean0 = vdupq_n_f32(mean[0]);
  float32x4_t vmean1 = vdupq_n_f32(mean[1]);
  float32x4_t vmean2 = vdupq_n_f32(mean[2]);
  float32x4_t vscale0 = vdupq_n_f32(scale[0]);
  float32x4_t vscale1 = vdupq_n_f32(scale[1]);
  float32x4_t vscale2 = vdupq_n_f32(scale[2]);

  float *dout_c0 = dout;
  float *dout_c1 = dout + size;
  float *dout_c2 = dout + size * 2;

  int i = 0;
  for (; i < size - 3; i += 4) {
    float32x4x3_t vin3 = vld3q_f32(din);
    float32x4_t vsub0 = vsubq_f32(vin3.val[0], vmean0);
    float32x4_t vsub1 = vsubq_f32(vin3.val[1], vmean1);
    float32x4_t vsub2 = vsubq_f32(vin3.val[2], vmean2);
    float32x4_t vs0 = vmulq_f32(vsub0, vscale0);
    float32x4_t vs1 = vmulq_f32(vsub1, vscale1);
    float32x4_t vs2 = vmulq_f32(vsub2, vscale2);
    vst1q_f32(dout_c0, vs0);
    vst1q_f32(dout_c1, vs1);
    vst1q_f32(dout_c2, vs2);

    din += 12;
    dout_c0 += 4;
    dout_c1 += 4;
    dout_c2 += 4;
  }
  for (; i < size; i++) {
    *(dout_c0++) = (*(din++) - mean[0]) * scale[0];
    *(dout_c1++) = (*(din++) - mean[1]) * scale[1];
    *(dout_c2++) = (*(din++) - mean[2]) * scale[2];
  }
}

void NHWC1ToNC1HW(const float *src, float *dst, const float *mean,
                  const float *std, int width, int height) {
  int size = height * width;
  float32x4_t vmean = vdupq_n_f32(mean ? mean[0] : 0.0f);
  float32x4_t vscale = vdupq_n_f32(std ? (1.0f / std[0]) : 1.0f);
  int i = 0;
  for (; i < size - 3; i += 4) {
    float32x4_t vin = vld1q_f32(src);
    float32x4_t vsub = vsubq_f32(vin, vmean);
    float32x4_t vs = vmulq_f32(vsub, vscale);
    vst1q_f32(dst, vs);
    src += 4;
    dst += 4;
  }
  for (; i < size; i++) {
    *(dst++) = (*(src++) - mean[0]) / std[0];
  }
}
`
