### ISSUE TITLE
通过修改图像分类的demo，top1、top2、top3预测结果准确，但概率相加不为1，且数值很大

### ISSUE THREAD

**Issue by NyquistBodeTu** [PaddlePaddle/Paddle-Lite-Demo#180]
我按照教程将Paddle-Lite-Demo的image_classification_demo改成自己的模型和标签文件后，每个预测指标数据均大于一，不知道哪里出错了
教程：https://www.bilibili.com/video/BV1s44y117T2?share_source=copy_web，
![微信图片_20220207232156](https://user-images.githubusercontent.com/94345348/152817529-c93865fd-853a-44dc-b30f-b079c04e9892.jpg)

**Comment by chenjiaoAngel** [comment]
模型的输入shape 和图像的预处理/后处理也是和image_classify 一模一样？辛苦check下是否要更新，另外模型路径和标签路径检查下是否修改生效

**Comment by PQ-girl** [comment]
你好，请问你解决了吗，我也是这种问题
