### ISSUE TITLE
请问如何在object_detection_demo基础上加载yolov3模型

### ISSUE THREAD

**Issue by zjyhll** [PaddlePaddle/Paddle-Lite-Demo#182]
![image](https://user-images.githubusercontent.com/8895877/153569740-7478e28f-48c4-4956-8cb1-62a137328ca4.png)
直接加载yolo_detection_demo项目下的yolov3模型会报错
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8172 (Predictor Worke), pid 8131 (bject_detection)

**Comment by zjyhll** [comment]
![image](https://user-images.githubusercontent.com/8895877/153572018-0ea18229-6a9d-484c-8b3d-e309aa726f67.png)
inputShape 这些改了同样会报错
 protected long[] inputShape = new long[]{1, 3, 320, 320};
 protected float[] inputMean = new float[]{0.485f, 0.456f, 0.406f};
 protected float[] inputStd = new float[]{0.229f, 0.224f, 0.225f};
![image](https://user-images.githubusercontent.com/8895877/153572090-1424ffce-3b18-48f6-8094-f2ec39208cbc.png)

**Comment by zjyhll** [comment]
已自行找到办法

**Comment by fanjianchao1983** [comment]
我也遇到相同的问题，大神是怎么解决的？
