### ISSUE TITLE
iOS自定义的视频流转换成UIImage，再调用UIImageToMat去识别，发现识别可性度很低

### ISSUE THREAD

**Issue by lxm1799** [PaddlePaddle/Paddle-Lite-Demo#183]
自己的iOS工程中，将视频流转换成UIImage，然后再调用UIImageToMat去识别，发现识别可性度很低，然而demo中的视频流代理- (void)processImage:(cv::Mat &)image是直接转换成C++的，识别率却很高。

即使将demo中(void)processImage:(cv::Mat &)image的image先通过MatToUIImage转换成UIImage，识别率依然没有问题。

所以我猜测是视频流中processImage做了什么处理，跟直接使用UIImageToMat处理成C++图片还是有点区别的，请告诉我该如何解决这个问题。

经过测试发现，自己工程中获取到视频流转换成UIImage时，先处理成NSData确定其格式类型，然后在转换成UIImage识别率才会正确，也就是说一定要给确定的图片格式才行。

**Comment by Charlotte3240** [comment]
@lxm1799  大佬我现在也遇到了这个问题，但是没有找到demo中的 cvimage 是在哪里赋值的。 我现在就不能从uiimage 转到 mat

**Comment by lxm1799** [comment]
@Charlotte3240 
如果你只是简单的想通过静态图片获取到检测分数，可以看看我的一个库：https://github.com/lxm1799/FaceMediapipe
可以直接集成到你的iOS项目中，安卓的官方直接支持，具体参考Mediapipe官网。
如果你一定要使用PaddlePaddle的话，我这边历史代码有修复，也可以找出来。

**Comment by Charlotte3240** [comment]
@lxm1799  谢谢大佬了 我这边还是要用paddle的，不是我能决定的  而且不一定用于检测分数，还有其他作用，如果有解决方案能贴出来的话 不胜感激

**Comment by lxm1799** [comment]
@Charlotte3240 
我贴出来具体代码，你自己负责一下在项目里面看看：

#import "Face.h"
#import <sys/timeb.h>
#import <opencv2/opencv.hpp>
#import <opencv2/highgui/ios.h>
#import <opencv2/highgui/cap_ios.h>

#include <iostream>
#include <vector>
#include <string>
#include <arm_neon.h>
#include <mutex>
#include "paddle_api.h"
#include "paddle_use_ops.h"
#include "paddle_use_kernels.h"
#include "timer.h"




using namespace paddle::lite_api;
using namespace cv;

struct Object{
    int batch_id;
    cv::Rect rec;
    int class_id;
    float prob;
};

std::mutex mtx;
std::shared_ptr<PaddlePredictor> net_mbv1;
Timer tic;
long long count = 0;

double tensor_mean(const Tensor& tin) {
    auto shape = tin.shape();
    int64_t size = 1;
    for (int i = 0; i < shape.size(); i++) {
        size *= shape[i];
    }
    double mean = 0.;
    auto ptr = tin.data<float>();
    for (int i = 0; i < size; i++) {
        mean += ptr[i];
    }
    return mean / size;
}

void neon_mean_scale(const float* din, float* dout, int size, std::vector<float> mean, std::vector<float> scale) {
    float32x4_t vmean0 = vdupq_n_f32(mean[0]);
    float32x4_t vmean1 = vdupq_n_f32(mean[1]);
    float32x4_t vmean2 = vdupq_n_f32(mean[2]);
    float32x4_t vscale0 = vdupq_n_f32(1.f / scale[0]);
    float32x4_t vscale1 = vdupq_n_f32(1.f / scale[1]);
    float32x4_t vscale2 = vdupq_n_f32(1.f / scale[2]);
    
    float* dout_c0 = dout;
    float* dout_c1 = dout + size;
    float* dout_c2 = dout + size * 2;
    
    int i = 0;
    for (; i < size - 3; i += 4) {
        float32x4x3_t vin3 = vld3q_f32(din);
        float32x4_t vsub0 = vsubq_f32(vin3.val[0], vmean0);
        float32x4_t vsub1 = vsubq_f32(vin3.val[1], vmean1);
        float32x4_t vsub2 = vsubq_f32(vin3.val[2], vmean2);
        float32x4_t vs0 = vmulq_f32(vsub0, vscale0);
        float32x4_t vs1 = vmulq_f32(vsub1, vscale1);
        float32x4_t vs2 = vmulq_f32(vsub2, vscale2);
        vst1q_f32(dout_c0, vs0);
        vst1q_f32(dout_c1, vs1);
        vst1q_f32(dout_c2, vs2);
        
        din += 12;
        dout_c0 += 4;
        dout_c1 += 4;
        dout_c2 += 4;
    }
    for (; i < size; i++) {
        *(dout_c0++) = (*(din++) - mean[0]) / scale[0];
        *(dout_c1++) = (*(din++) - mean[1]) / scale[1];
        *(dout_c2++) = (*(din++) - mean[2]) / scale[2];
    }
}


// fill tensor with mean and scale, neon speed up
void preprocess(const Mat& img_in, Tensor& tout, int width, int height,
                            std::vector<float> mean, std::vector<float> scale, bool is_scale) {
    if (img_in.channels() == 4) {
        cv::cvtColor(img_in, img_in, CV_RGBA2RGB);
    }
    
    cv::Size size = cv::Size(width, height);
    cv::Mat im;
    cv::resize(img_in, im, size, 0.f, 0.f);
    cv::Mat imgf;
    float scale_factor = is_scale? 1 / 255.f : 1.f;
    im.convertTo(imgf, CV_32FC3, scale_factor);
    const float* dimg = reinterpret_cast<const float*>(imgf.data);
    float* dout = tout.mutable_data<float>();
    neon_mean_scale(dimg, dout, width * height, mean, scale);
}

const char* class_names[] = {
    "background",
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    "tvmonitor"
};



std::vector<Object> detect_object(const float* data,
                                    int count,
                                    const std::vector<std::vector<uint64_t>>& lod,
                                    const float thresh,
                                    Mat& image) {
    std::vector<Object> rect_out;
    const float* dout = data;
    for (int iw = 0; iw < count; iw++) {
        int oriw = image.cols;
        int orih = image.rows;
        if (dout[1] > thresh && static_cast<int>(dout[0]) > 0) {
            Object obj;
            int x = static_cast<int>(dout[2] * oriw);
            int y = static_cast<int>(dout[3] * orih);
            int w = static_cast<int>(dout[4] * oriw) - x;
            int h = static_cast<int>(dout[5] * orih) - y;
            cv::Rect rec_clip = cv::Rect(x, y, w, h) & cv::Rect(0, 0, image.cols, image.rows);
            obj.batch_id = 0;
            obj.class_id = static_cast<int>(dout[0]);
            obj.prob = dout[1];
            obj.rec = rec_clip;
            

            NSLog(@"prob = %f  class_name = %s",obj.prob,class_names[obj.class_id]);
            
            if (w > 0 && h > 0 && obj.prob <= 1) {
                rect_out.push_back(obj);
                cv::rectangle(image, rec_clip, cv::Scalar(255, 0, 0));
                
                std::cout << "detection, image size: " << image.cols
                << ", " << image.rows << ", detect object: "
                << class_names[obj.class_id] << ", score: "
                << obj.prob << ", location: x=" << x << ", y="
                << y << ", width=" << w << ", height=" << h << std::endl;
            }
        }
        dout += 6;
    }
    return rect_out;
}


std::vector<Object> detect_object1(const float* data,
                                    int count,
                                    const std::vector<std::vector<uint64_t>>& lod,
                                    const float thresh,
                                    Mat& image) {
    std::vector<Object> rect_out;
    const float* dout = data;
    for (int iw = 0; iw < count; iw++) {
        if (dout[1] > thresh && static_cast<int>(dout[0]) > 0) {
            Object obj;
            obj.batch_id = 0;
            obj.class_id = static_cast<int>(dout[0]);
            obj.prob = dout[1];
            rect_out.push_back(obj);
            NSLog(@"prob = %f  class_name = %s",obj.prob,class_names[obj.class_id]);
        }
        dout += 6;
    }
    return rect_out;
}

std::vector<Object> detect_object2(const float* data,
                                    int count,
                                    const float thresh) {
    std::vector<Object> rect_out;
    const float* dout = data;
    for (int iw = 0; iw < count; iw++) {
        NSLog(@"koma dout %f", dout[1]);
        if (dout[1] > thresh) {
            Object obj;
            obj.batch_id = 0;
            obj.prob = dout[1];
            rect_out.push_back(obj);
        } else {
            break;
        }
        dout += 6;
    }
    return rect_out;
}



#pragma mark --类Face

@interface Face()

@property (nonatomic) bool flag_init;
@property (nonatomic) bool flag_cap_photo;
@property (nonatomic) std::vector<float> scale;
@property (nonatomic) std::vector<float> mean;
@property (nonatomic) int input_height;
@property (nonatomic) int input_width;
@property (nonatomic) std::vector<std::string> labels;
@property (nonatomic) cv::Mat cvimg;

@end





@implementation Face


/**
 *
 * 根据图片数据获取图片的原始类型
 *
 * @param data 图片的二进制数据
 * @return 图片的实际格式
 */
- (NSString *)typeForImageData:(NSData *)data {
    uint8_t c;
    [data getBytes:&c length:1];
    
    switch (c) {
        case 0xFF:
            return @"image/jpeg";
        case 0x89:
            return @"image/png";
        case 0x47:
            return @"image/gif";
        case 0x49:
        case 0x4D:
            return @"image/tiff";
        case 0x52: {
            //R as RIFF for WEBP
            if (data.length < 12) {
                return nil;
            }
            NSString *identifierTypeStr = [[NSString alloc] initWithData:[data subdataWithRange:NSMakeRange(0, 12)] encoding:NSASCIIStringEncoding];
            if ([identifierTypeStr hasPrefix:@"RIFF"] && [identifierTypeStr hasSuffix:@"WEBP"]) {
                return @"image/webp";
            }
            return nil;
        }
            
        default:
            break;
    }
    return nil;
}

-(void)dected:(UIImage *)image count:(NSInteger)count callback:(void(^)(BOOL isTogether,NSInteger count))callback{
//    dispatch_queue_t queue = dispatch_queue_create("dected.com", DISPATCH_QUEUE_CONCURRENT);
//    dispatch_async(queue, ^{
//        [self dectedAction:image count:count callback:callback];
//    });
    [self dectedAction:image count:count callback:callback];
}

///识别精度
#define kVertiflyScore  0.6

-(void)dectedAction:(UIImage *)image count:(NSInteger)count callback:(void(^)(BOOL isTogether,NSInteger count))callback{
    ///注意：
    ///UIImage的格式一定要确定，不如是png,jpg,否则是无法识别滴
    ///如果从视频流获取的UIImage是不带格式的，先通过转换成data,然后在此转换成UIImage才行
    
    ///官方模型参数数据
    self.mean = {0.5f, 0.5f, 0.5f};
    self.scale = {0.5f, 0.5f, 0.5f};
    self.input_width = 640;
    self.input_height = 360;

    // 1. 设置 MobileConfig
    paddle::lite_api::MobileConfig config;
    NSString *path = [[NSBundle mainBundle] bundlePath];
    std::string paddle_mobilenetv1_dir = std::string([path UTF8String]);

    config.set_model_from_file(paddle_mobilenetv1_dir + "/blazeface_nofpn_mini_model.nb");

    config.set_threads(3); // 设置工作线程数
    // 2. 创建 PaddlePredictor
    net_mbv1 = CreatePaddlePredictor<MobileConfig>(config);
    cv::Mat img_cat;
    UIImageToMat(image, img_cat);
    
    cv::Mat img;
    if (img_cat.channels() == 4) {
        cv::cvtColor(img_cat, img, CV_RGBA2RGB);
    }
    
    if (img.empty()) {
        NSLog(@"------图片没有数据------");
        return;
    }

    // 3. 设置输入数据
    std::unique_ptr<Tensor> input_tensor(net_mbv1->GetInput(0));
    input_tensor->Resize({1, 2});
    auto* data = input_tensor->mutable_data<float>();
    data[0] = self.input_height;
    data[1] = self.input_width;
    
    std::unique_ptr<Tensor> input_tensor2(net_mbv1->GetInput(1));
    input_tensor2->Resize({1, 3, self.input_height, self.input_width});
    input_tensor2->mutable_data<float>();
    //预处理数据
    preprocess(img, *(input_tensor2.get()),self.input_width,self.input_height, self.mean, self.scale, true);
    
    std::unique_ptr<Tensor> input_tensor3(net_mbv1->GetInput(2));
    input_tensor3->Resize({1, 2});
    auto* data3 = input_tensor3->mutable_data<float>();
    data3[0] = 1;
    data3[1] = 1;
    
    ///开启定时器
    tic.start();
    // 4. 执行预测
    net_mbv1->Run();
    ///结束定时器
    tic.end();
    
    // 5. 获取输出数据,取出tensor里面的第一个数据
    std::unique_ptr<const Tensor> output_tensor(net_mbv1->GetOutput(0));
    //拿到一个指针二维数组
    auto ptr = output_tensor->mutable_data<float>();
    auto shape_out = output_tensor->shape();
    
    int64_t cnt = 1;
    for (auto& i : shape_out) {
        cnt *= i;
    }
    ///取到tensor里面的第一个数据，然后转换成数组，再取数组里面的【0】【1】数据
    auto rec_out = detect_object2(ptr, static_cast<int>(cnt / 6), kVertiflyScore);

    long realCount = rec_out.size();
    if (callback != nil) {
        callback(realCount == count, realCount);
    }
}
@end

**Comment by Charlotte3240** [comment]
多谢

**Comment by Charlotte3240** [comment]
问题解决了

主要代码是这几行
```
    cv::Mat img;
    cv::Mat tmpImg;
    // 从UIImage中读取图片生成矩阵 tmpImg
    UIImageToMat(_image, tmpImg);
    if (img.channels() == 4) {
        cv::cvtColor(tmpImg, img, CV_RGBA2RGB);
    }else{
        img = tmpImg;
    }
    if (img.empty()) {
        NSLog(@"------图片没有数据------");
        return;
    }


```
