### ISSUE TITLE
求arm版yolo demo里的原始模型。

### ISSUE THREAD

**Issue by Taichipeace** [PaddlePaddle/Paddle-Lite-Demo#187]
各位大佬好！
我在arm架构的cpu上面跑 [Paddle-Lite-Demo]/[PaddleLite-armlinux-demo]/yolo_detection_demo/
因为自己编译了 .so文件库，现在需要用同样的版本的opt工具再次转换yolo模型。
demo里给出的nb模型是17MB：yolov3_mobilenet_v3_prune86_FPGM_320_fp32_for_cpu_v2_10_rc.tar.gz
但是我用PaddleDetection里的 MobileNet-V3-SSLD 320 转换之后的模型是97MB，转换时也加了  --tailored参数。
请问可以提供17MB .nb模型对应的原始模型吗？

**Comment by sprouteer** [comment]
[yolov3_mobilenet_v3_prune86_FPGM_320_fp32_fluid.tar.gz](https://github.com/PaddlePaddle/Paddle-Lite-Demo/files/8169652/yolov3_mobilenet_v3_prune86_FPGM_320_fp32_fluid.tar.gz)

**Comment by Taichipeace** [comment]
> [yolov3_mobilenet_v3_prune86_FPGM_320_fp32_fluid.tar.gz](https://github.com/PaddlePaddle/Paddle-Lite-Demo/files/8169652/yolov3_mobilenet_v3_prune86_FPGM_320_fp32_fluid.tar.gz)

非常感谢！
