### ISSUE TITLE
代码拉不下来

### ISSUE THREAD

**Issue by xinnian88** [PaddlePaddle/Paddle-Lite-Demo#20]
Downloading ios-classification_demo/classification_demo/opencv2.framework/Versions/A/opencv2 (145 MB)
Error downloading object: ios-classification_demo/classification_demo/opencv2.framework/Versions/A/opencv2 (cce4b43): Smudge error: Error downloading ios-classification_demo/classification_demo/opencv2.framework/Versions/A/opencv2 (cce4b4336d6136ef4029e9ab9b627212a5520e6393429247fd7c10c491ac6ff7): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /Users/xinnian/workspace/Paddle-Lite-Demo/.git/lfs/logs/20191006T205605.103015.log
Use `git lfs logs last` to view the log.
error: 外部过滤器 'git-lfs filter-process' 失败
fatal: ios-classification_demo/classification_demo/opencv2.framework/Versions/A/opencv2：smudge 过滤器 lfs 失败

**Comment by hong19860320** [comment]
代码仓库有点大且最近github访问速度较慢，建议多尝试几次或采用其它方法加速github的访问。

**Comment by mzchtx** [comment]
> 代码仓库有点大且最近github访问速度较慢，建议多尝试几次或采用其它方法加速github的访问。

遇到同样的问题

**Comment by hong19860320** [comment]
> > 代码仓库有点大且最近github访问速度较慢，建议多尝试几次或采用其它方法加速github的访问。
> 
> 遇到同样的问

**Comment by hong19860320** [comment]
已经将模型和库文件从repo中移除，采用编译时下载方式，建议直接在主页上clone master分支。
