### ISSUE TITLE
libpaddle_api_light_bundled.a 这个库有没有armv7版本呀

### ISSUE THREAD

**Issue by sqm911** [PaddlePaddle/Paddle-Lite-Demo#203]
libpaddle_api_light_bundled.a 这个库有没有armv7版本呀

**Comment by hellomjx** [comment]
同问

**Comment by chenjiaoAngel** [comment]
有的，可以去paddle-lite release 界面下载V7 预测库。
https://github.com/PaddlePaddle/Paddle-Lite/tags
