### ISSUE TITLE
树莓派32/64位系统编译安装2.10版本paddlelite版本号乱码， 官方demo无法run.sh

### ISSUE THREAD

**Issue by sdjxmikill** [PaddlePaddle/Paddle-Lite-Demo#212]
![推理失败](https://user-images.githubusercontent.com/20013022/160113209-ed54dd88-84eb-4b74-8e87-58724c856a36.png)
![版本号错误](https://user-images.githubusercontent.com/20013022/160113275-0e57e59b-0a53-449a-bcaa-9ed4db705a9f.png)
树莓派4B8G，安装的树莓派官方os64位和32位都经过了10多次的安装编译（32位能用csi摄像头，64位不行），版本号乱码问题没有解决，官方的demo跑不起来（是不是必须要安装opencv，opencv我也安装成功了过程很痛苦，但是依旧不能把demo跑起来），希望老师能尽快给答疑解惑，新手上路太难了，希望老师们能够给予详细解答，万分感谢！！！
2022-01-28-raspios-bullseye-arm64
和
2022-01-28-raspios-bullseye-armhf

**Comment by chenjiaoAngel** [comment]
请问使用的模型有更新吗？还是demo的模型呢？
根据log看，好像是模型的输入shape/输入tensor 个数不太对

**Comment by sdjxmikill** [comment]
> 

我用的官方的demo

**Comment by sdjxmikill** [comment]
版本错误的问题如何解决呢，如果不解决是不是没有影响？demo是当前官方github上面的

**Comment by chenjiaoAngel** [comment]
如果是warning，那没有影响。否则，建议升级版本，保持OPT版本和预测库版本一样

**Comment by sdjxmikill** [comment]
> 如果是warning，那没有影响。否则，建议升级版本，保持OPT版本和预测库版本一样

在Linux下安装官方流程进行make编译安装后，得到的whl版本如图所示是乱码，尝试了6次编译都是如此，不知是何原因。这是安装过程 https://www.cnblogs.com/sdjxcolin/p/15981285.html

**Comment by mjp9527** [comment]
版本号不是乱码，是commit，表示当前用的库最新的编译commit
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/54735487/162658183-b14182a3-92ff-441c-9709-e53c4ad43cec.png">

**Comment by mjp9527** [comment]
从这个commit看，你用的应该不是release编译库，建议从这个commit重新编译一下opt再转换模型，或者替换动态库为v2.10-rc版本  https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.10-rc
