### ISSUE TITLE
在arm_linux（银河麒麟）机器上编译object_detection_demo出现很多"对'xxx()'未定义"的错误

### ISSUE THREAD

**Issue by sunlin-git** [PaddlePaddle/Paddle-Lite-Demo#233]
CMakeFiles/object_detection_demo.dir/yolov3_mobile_api.cc.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
yolov3_mobile_api.cc:(.text+0xa0c)：对‘touch_op_fill_any_like()’未定义的引用
yolov3_mobile_api.cc:(.text+0xa20)：对‘touch_op_shape()’未定义的引用
yolov3_mobile_api.cc:(.text+0xa34)：对‘touch_op_sequence_pool()’未定义的引用
yolov3_mobile_api.cc:(.text+0xa48)：对‘touch_op_matrix_nms()’未定义的引用
yolov3_mobile_api.cc:(.text+0xa5c)：对‘touch_op_yolo_box()’未定义的引用
....

**Comment by sunlin-git** [comment]
目标机器为飞腾银河麒麟

**Comment by chenjiaoAngel** [comment]
这个看起来，是不是paddle 的include 头文件没有包含？或者预测库更新了，但头文件没有更新？

**Comment by sunlin-git** [comment]
@chenjiaoAngel 谢谢，头文件是包含了，我检验一下后者。

**Comment by sunlin-git** [comment]
@chenjiaoAngel 可以了，是头文件包含多了。只需要包含“paddle_api.h”就行了
