### ISSUE TITLE
develop分支ocr/ppocr安卓项目报错。

### ISSUE THREAD

**Issue by deepthman** [PaddlePaddle/Paddle-Lite-Demo#235]
完全按照流程来弄的，第一次编译运行报错找不到模型无法加载。看了MainActivity.java的路径，确实不对，把模型直接放到assets文件夹下可以加载模型。
之后编译运行app可以跑起来，但是只能跑出检测的效果，并报了以下错误：
````none
I/Paddle-Lite: [I  4/22 10:14:37. 37 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
I/Paddle-Lite: [I  4/22 10:14:37. 37 ...0rc/Paddle-Lite/lite/core/device_info.cc:1139 Setup] Total memory: 2853016KB
E/cv::error(): OpenCV(4.2.0) Error: Assertion failed (!_src.empty()) in cvtColor, file /build/master_pack-android/opencv/modules/imgproc/src/color.cpp, line 182
E/libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(4.2.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17905 (GLThread 44671)

````
app的截图
![Screenshot_20220422-103403](https://user-images.githubusercontent.com/50742242/164585314-05c440c2-fa6c-44ab-b11b-6f217fad6772.jpg)

**Comment by chenjiaoAngel** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/38650344/164960442-2a1ae8d3-f7f1-4d85-9e69-8040826803a8.png">
这个错误看起来是图片路径给的不对，显示图片是空，opencv 处理报错

**Comment by deepthman** [comment]
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/38650344/164960442-2a1ae8d3-f7f1-4d85-9e69-8040826803a8.png">
> 
> 这个错误看起来是图片路径给的不对，显示图片是空，opencv 处理报错

问题是找到了，在CameraSurfaceView.java里42,43行的两个变量初始值不为0就可以。
但是app运行后也是只能看到预测框，调试可以看到已经识别到文字。这个demo的效果是不展示识别到的文字吗？

**Comment by chenjiaoAngel** [comment]
这个demo是可以看到预测的框，框里标注的是文字。请问识别到的文字是指？
<img width="269" alt="image" src="https://user-images.githubusercontent.com/38650344/165012241-fff683ec-0306-4d65-ba78-5f2715d3debf.png">

**Comment by deepthman** [comment]
> 这个demo是可以看到预测的框，框里标注的是文字。请问识别到的文字是指？ <img alt="image" width="269" src="https://user-images.githubusercontent.com/38650344/165012241-fff683ec-0306-4d65-ba78-5f2715d3debf.png">

我的意思是，demo效果只能看到文字检测的框吗，识别出来的文字并不展示？我看代码里可以把文字识别出来，效果只有文字检测的框。因为md里的效果图一直加载不出来，不知道效果应该是怎样的。

**Comment by chenjiaoAngel** [comment]
嗯，只是展示，识别出来的文字不会在app 显示。APP如果显示这个话，内容有些多，看起来可能不太直观。如果您有好的排版 方式去解决的话，辛苦帮忙提代码修改，感谢～

**Comment by deepthman** [comment]
> 嗯，只是展示，识别出来的文字不会在app 显示。APP如果显示这个话，内容有些多，看起来可能不太直观。如果您有好的排版 方式去解决的话，辛苦帮忙提代码修改，感谢～

好的，谢谢告知。

**Comment by DuanchuWang** [comment]
朋友你的配置是什么QAQ我把模型放进去就报错了

**Comment by woodboard** [comment]
请问在哪里获取识别到的文字

**Comment by deepthman** [comment]
> 个demo的效果是不展示识别

模型输出那里，手动print在控制台可以看到。这个要撸代码看流程是在哪里得到文字。年代有点久远具体位置不记得了，印象中是通过指针拿到的概率，然后映射成文字。

**Comment by deepthman** [comment]
> 请问在哪里获取识别到的文字

模型输出那里，手动print在控制台可以看到。这个要撸代码看流程是在哪里得到文字。年代有点久远具体位置不记得了，印象中是通过指针拿到的概率，然后映射成文字。
