### ISSUE TITLE
关于object_detection iOS demo中的neon加速部分的疑问

### ISSUE THREAD

**Issue by lip0041** [PaddlePaddle/Paddle-Lite-Demo#243]
https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/develop/object_detection/ios/ssd_mobilenetv1_demo/detection_demo/ViewController.mm

链接中的代码里有两个关于neon的函数，应该是被用于预处理。

但是我通过查找，发现函数double tensor_mean(const Tensor &tin) 好像没有被其他函数调用，请问这个函数还有必要存在在项目中吗？

另外，另一个函数void neon_mean_scale(const float *din, float *dout, int size, float *mean, float *scale)的原理可以讲解一下吗？或者我应该去哪里去找相关的内容呢？我有搜过neon相关的东西，但大部分是android端的，iOS的内容很少。

**Comment by chenjiaoAngel** [comment]
double tensor_mean(const Tensor &tin)  这个是求tensor 的均值，我们在debug精度的时候，可能用到
oid neon_mean_scale(const float *din, float *dout, int size, float *mean, float *scale) 这个是输入数据的归一化处理，即：(din-mean)/scale。有利用C_intrisic 指令进行加速，并行做4个数据处理

**Comment by lip0041** [comment]
> double tensor_mean(const Tensor &tin) 这个是求tensor 的均值，我们在debug精度的时候，可能用到
> oid neon_mean_scale(const float *din, float *dout, int size, float *mean, float *scale) 这个是输入数据的归一化处理，即：(din-mean)/scale。有利用C_intrisic 指令进行加速，并行做4个数据处理

谢谢解答🙏
