### ISSUE TITLE
MacOS x64 编译OCR demo，及运行时的问题

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/Paddle-Lite-Demo#255]
Hi, 
我最近将paddle-lite ocr的demo 部署到各个平台，目前android，ios平台已根据示例代码全部跑通。
MacOS M1 平台也已经跑通，也把PaddleOCR提供的PP-OCR-V3的模型根据OPT转换成功，并成功在M1平台上运行。

但是当我把相同代码运行到MacOS x64时，出现了一些问题

第一：x64平台缺少头文件#include <arm_neon.h>
所以我使用了intel的ARM_NEON_2_x86_SSE来替代
`https://github.com/intel/ARM_NEON_2_x86_SSE.git`

解决了不能使用arm加速的问题。

但是识别模型出现了一些问题。不能识别长串的字符。
检测模型是非常好的运行的。
请问这个是什么情况导致的呢？

并有的时候在识别时会出现崩溃
日志已上传，带log和export GLOG_v=5的日志
(59892,0x10c7dddc0) malloc: Incorrect checksum for freed object 0x7fc32682ec00: probably modified after being freed.
[log.txt](https://github.com/PaddlePaddle/Paddle-Lite-Demo/files/8639562/log.txt)

我用build.lite.x86/inference_lite_lib/demo/cxx/mobilenetv1_full 去检测并生成nb模型的时候会出现以下段错误
[log.txt](https://github.com/PaddlePaddle/Paddle-Lite-Demo/files/8639611/log.txt)

我使用的paddle-lite版本：tag为v2.11-rc的版本
需要转换模型为：https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar

**Comment by chenjiaoAngel** [comment]
你是用的X86 CPU 进行跑吗？当前lite 的X86 暂不支持量化模型，支持也不太完善。我们目前在集成openvino ,集成完成后，这些模型应该可以运行

**Comment by ANDROIDTODO** [comment]
@chenjiaoAngel 好的。如果有消息麻烦通知一下哈

**Comment by yangy996** [comment]
大佬知道为什么我运行项目会报这个错误呢？
![image](https://user-images.githubusercontent.com/15188456/199419931-ec8db51d-c6ab-4d71-a0eb-a507c89b100e.png)
