### ISSUE TITLE
not supported dtype 6

### ISSUE THREAD

**Issue by premeditate** [PaddlePaddle/Paddle-Lite-Demo#258]
我下载object_detection_demo能够正常运行

将model.nb换成自己的模型后运行程序闪退,在logcat中出现一下日志
```
2022-05-07 10:31:55.088 21757-22430/com.baidu.paddle.lite.demo.object_detection A/Paddle-Lite: [F  5/ 7 10:31:55. 88 ...te/kernels/host/fill_constant_compute.cc:50 Run] not supported dtype 6
2022-05-07 10:31:55.089 21757-22430/com.baidu.paddle.lite.demo.object_detection E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F  5/ 7 10:31:55. 88 ...te/kernels/host/fill_constant_compute.cc:50 Run] not supported dtype 6
2022-05-07 10:31:55.089 21757-22430/com.baidu.paddle.lite.demo.object_detection A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22430 (Predictor Worke), pid 21757 (bject_detection)
```

请问dtype 6是什么呢

**Comment by premeditate** [comment]
我转换的模型输入是这样子的

![微信图片_20220507165144](https://user-images.githubusercontent.com/85290082/167247007-df49e198-7681-4903-833d-4b67d646b488.png)

增加的输入处理代码为这个

![微信图片_20220507165300](https://user-images.githubusercontent.com/85290082/167247015-0fc1d2b3-f1fc-4d65-b24c-182172a489b6.png)

然后编译报的错误就是这个

![微信图片_20220507165316](https://user-images.githubusercontent.com/85290082/167247019-c6846cf7-87f6-4b61-8760-5c1c066acec7.png)

看了issue也是说dytpe 6是FP64,但是我不知道在哪里改这个

paddle lite 和paddle lite demo相关的issue我都有看,但是最终还是没解决,官方的issue问题也是没解决

我是用paddlex gui训练的模型,没有哪里设置这个数据类型的,然后用的是paddle lite 2.10rc的opt工具

转换nb模型的代码是这个

![微信图片_20220507165359](https://user-images.githubusercontent.com/85290082/167247036-7c897cf5-a1df-4a01-bf17-2c45223ad32e.jpg)

paddlex gui导出是没有数据类型配置的,但是我查了一下paddlex的 api导出命令,看参数说明,也没有哪里设置输出数据类型

![微信图片_20220507165421](https://user-images.githubusercontent.com/85290082/167247051-f86607bd-b058-438d-9d3d-f30a9bbf7a24.png)

**Comment by chenjiaoAngel** [comment]
这个应该是fill_constant op 不支持float64 计算类型，这个可以在模型仓库，问问模型同学怎么修改

**Comment by yghstill** [comment]
@premeditate PaddleDetection中导出的模型请使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/lite  进行部署

**Comment by yghstill** [comment]
@premeditate 
你的模型是什么？yolov3？
目标检测模型可以使用PaddleDetection导出，并试用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/lite 进行部署，支持image、scale_factor、im_shape多输入传入。

**Comment by leiqing1** [comment]
解决思路：
1. 安装paddledetection，使用paddleDetection里面的export代码，进行代码导出操作，即可保证模型参数否是float32的。譬如如果是picodet，可以参考如下链接中导出模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet
`例如：导出模型：
$:cd PaddleDetection
$:python tools/export_model.py -c configs/picodet/picodet_s_320_coco_lcnet.yml \
              -o weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco_lcnet.pdparams \
              --output_dir=output_inference`

原因分析：
1.是因为训练Paddlex里面导出模型时，处理有问题导致fill_constant op弄成了float64造成的。询问了下PaddleDetection等，默认都是float32训练、导出的。

后续优化点：
1. 可以在opt（模型转化工具）中强制做一个类型转换，并提醒用户，有不支持的模型格式，已转换成支持格式**等。

**Comment by premeditate** [comment]
> 

我的模型是用paddleX GUI进行训练的,使用的模型是picodet,骨干网络是mobileV3训练出来的目标检测模型

**Comment by premeditate** [comment]
@yghstill 我的模型是用paddleX GUI进行训练的,使用的模型是picodet,骨干网络是mobileV3训练出来的目标检测模型

**Comment by premeditate** [comment]
@leiqing1 是要用PaddleDetection将我们的模型重新训练一次吗?

**Comment by premeditate** [comment]
> 解决思路：
> 
> 1. 安装paddledetection，使用paddleDetection里面的export代码，进行代码导出操作，即可保证模型参数否是float32的。譬如如果是picodet，可以参考如下链接中导出模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet
>    `例如：导出模型： $:cd PaddleDetection $:python tools/export_model.py -c configs/picodet/picodet_s_320_coco_lcnet.yml \ -o weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco_lcnet.pdparams \ --output_dir=output_inference`
> 
> 原因分析： 1.是因为训练Paddlex里面导出模型时，处理有问题导致fill_constant op弄成了float64造成的。询问了下PaddleDetection等，默认都是float32训练、导出的。
> 
> 后续优化点：
> 
> 1. 可以在opt（模型转化工具）中强制做一个类型转换，并提醒用户，有不支持的模型格式，已转换成支持格式**等。

@leiqing1 是要用PaddleDetection将我们的模型重新训练一次吗?

**Comment by premeditate** [comment]
> @premeditate 你的模型是什么？yolov3？ 目标检测模型可以使用PaddleDetection导出，并试用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/lite 进行部署，支持image、scale_factor、im_shape多输入传入。

@yghstill 我的模型是用paddleX GUI进行训练的,使用的模型是picodet,骨干网络是mobileV3训练出来的目标检测模型

**Comment by premeditate** [comment]
是模型的问题,之前的模型是使用paddleX GUI训练的,虽然最后能转成.nb格式的文件,但是不能使用.

**Comment by camelwoo** [comment]
> 是模型的问题,之前的模型是使用paddleX GUI训练的,虽然最后能转成.nb格式的文件,但是不能使用.

裁剪之后的模型应该可以用
