### ISSUE TITLE
picodet_detection_demo 如何显示目标检测结果数目

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/Paddle-Lite-Demo#273]
想在picodet_detection_demo中显示检测结果数目,,,但不太熟悉android app,,,,请问可以指点一下吗？

**Comment by mjp9527** [comment]
可以参考下README https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/picodet_detection_demo

**Comment by hobeter** [comment]
感谢
