### ISSUE TITLE
Check failed: (param_.axes[i] < in_dims.size()): 1!<0 The index of dimension in axes must be less than the size of input shape

### ISSUE THREAD

**Issue by huanghanguo** [PaddlePaddle/Paddle-Lite-Demo#274]
使用PaddleLite-android-demo/ssd_detection_demo示例项目，
报错信息：
`2022-05-31 17:22:39.395 15300-17513/com.baidu.paddle.lite.demo.ssd_detection A/Paddle-Lite: [F  5/31 17:22:39.395 ...c/Paddle-Lite/lite/operators/slice_op.cc:44 InferShapeImpl] Check failed: (param_.axes[i] < in_dims.size()): 1!<0 The index of dimension in axes must be less than the size of input shape.
2022-05-31 17:22:39.396 15300-17513/com.baidu.paddle.lite.demo.ssd_detection E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F  5/31 17:22:39.395 ...c/Paddle-Lite/lite/operators/slice_op.cc:44 InferShapeImpl] Check failed: (param_.axes[i] < in_dims.size()): 1!<0 The index of dimension in axes must be less than the size of input shape.
2022-05-31 17:22:39.396 15300-17513/com.baidu.paddle.lite.demo.ssd_detection A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17513 (GLThread 8941), pid 15300 (o.ssd_detection)`

[自己训练的模型输入信息入下：
[nb文件链接：](链接: https://pan.baidu.com/s/1p3BCDbwXkqtiwogseyBnOQ?pwd=t3na 提取码: t3na)
Paddle Lite v2.10-rc
1
name: image
type: float32[?,3,300,300]
2
name: scale_factor
type: float32[?,2]
0
name: im_shape
type: float32[?,2]
0
name: multiclass_nms3_0.tmp_0
type: float32[?,6]
1
name: multiclass_nms3_0.tmp_2
type: int32[?]

输入：
`void Detector::Preprocess(const cv::Mat &rgbaImage) {
  // Feed the input tensor with the data of the preprocessed image
  auto inputTensor = predictor_->GetInput(1);
  std::vector<int64_t> inputShape = {1, 3, inputHeight_, inputWidth_};
  inputTensor->Resize(inputShape);
  auto inputData = inputTensor->mutable_data<float>();
  cv::Mat resizedRGBAImage;
  cv::resize(rgbaImage, resizedRGBAImage,
             cv::Size(inputShape[3], inputShape[2]));
  cv::Mat resizedRGBImage;
  cv::cvtColor(resizedRGBAImage, resizedRGBImage, cv::COLOR_BGRA2RGB);
  resizedRGBImage.convertTo(resizedRGBImage, CV_32FC3, 1.0 / 255.0f);
  NHWC3ToNC3HW(reinterpret_cast<const float *>(resizedRGBImage.data), inputData,
               inputMean_.data(), inputStd_.data(), inputShape[3],
               inputShape[2]);`

**Comment by huanghanguo** [comment]
label_list

Mirror-Approximated
Thin-White
White-Greasy
Yellow-Greasy
Grey-Black

**Comment by nkhlS141** [comment]
did you find the solution for this?, facing the same issue....
