### ISSUE TITLE
picodet 在iOS上闪退

### ISSUE THREAD

**Issue by Cross2pro** [PaddlePaddle/Paddle-Lite-Demo#275]
picodet demo在iPad(iOS15.5)上闪退。
ssd_mobileNet可以正常运行。
但是picodet demo调试显示Thread 1: signal SIGABRT 闪退。

**Comment by liyancas** [comment]
您好，问题已经安排相关同学排查中

**Comment by AndSonder** [comment]
> 您好，问题已经安排相关同学排查中

所以现在是不是还没解决，我也遇到了一样的问题 @liyancas
