### ISSUE TITLE
出现多个框的问题

### ISSUE THREAD

**Issue by jeekMic** [PaddlePaddle/Paddle-Lite-Demo#276]
我的代码是https://github.com/ralph0813/Paddle_Lite_Object_Detection_Demo， 我把换了个训练模型，结果出现这样的现象
![device-2022-06-09-103753](https://user-images.githubusercontent.com/20333501/172752632-93c14010-6d61-4dd6-98cf-464b5352ab32.png)
  这张图片识我换了模型后的效果，上面连接是原始的模型，是正常都得，我想问下，出现这种情况是什么原因导致的呢，我更改下，或者需要我这边把模型发过去替换下试试吗

**Comment by mjp9527** [comment]
更换模型需要确认：模型的输入tensor个数、顺序、数据类型与原模型是否一致，不一致的话需要根据readme文档进行修改。还需确认模型的输出tensor个数、顺序、数据类型与原模型是否一致。同时确认标签文件等是否需要替换。

**Comment by jeekMic** [comment]
这个我都检查了，tensor个数、顺序、数据类型不一致都会直接报错，这种很多框也不知道是哪里不对

**Comment by mjp9527** [comment]
还有输入输出的维度，很多框是结果不正确，可能是后处理结果错误，也可能是模型推理结果有误，shell demo比较简单，可以拿shell demo测试一下

**Comment by jeekMic** [comment]
好的，这个我待会试下 ，我用 https://github.com/PaddlePaddle/Paddle-Lite-Demo.git 这个demo里面的 yolo_detection_demo也会出现很多框，但是把cmake中    ${PaddleLite_DIR}/cxx/libs/${ANDROID_ABI}/libpaddle_light_api_shared.so 换成  ${PaddleLite_DIR}/cxx/libs/${ANDROID_ABI}/libpaddle_lite_jni.so 就正常了，因为我现在项目是uvc相机，没办法通过纹理来处理，所以项直接通过java层处理图片的形式来处理回调的相机帧

**Comment by jeekMic** [comment]
另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理       
            public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢

**Comment by shiyuxin1999S** [comment]
![Screenshot_20220610_171838_com baidu paddle lite demo ssd_detection](https://user-images.githubusercontent.com/44061194/173036705-cf255bef-45c3-4b35-8ee4-08ab659a8965.jpg)
我也出现了相同的问题，请问怎么解决呢

**Comment by shiyuxin1999S** [comment]
感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的

**Comment by jeekMic** [comment]
> 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的

是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁

**Comment by shiyuxin1999S** [comment]
> > 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的
> 
> 是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁

大佬飞桨群人满了加不进去

**Comment by shiyuxin1999S** [comment]
> > 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的
> 
> 是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁

我觉得要不然试一下对第一个背景类不画框，然后在label文件第一行加一个background

**Comment by jeekMic** [comment]
> > > 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的
> > 
> > 
> > 是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁
> 
> 我觉得要不然试一下对第一个背景类不画框，然后在label文件第一行加一个background

你不绘制 就什么都没有了，界面上一个框都没有

**Comment by jeekMic** [comment]
> > > 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的
> > 
> > 
> > 是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁
> 
> 大佬飞桨群人满了加不进去
没用的，群里就几个技术人员，我们这些小问题，基本上不会帮我们解决，我加进去好久了，没效果，得自己找资料

**Comment by mjp9527** [comment]
> > > > 感觉好像是模型把所有的背景都给标出来了，但是实际上训练的时候label是没有背景的
> > > 
> > > 
> > > 是啊，替换模型就这样，很苦恼，另外我这想处理相机帧，不想通过opengl的方式，很愁
> > 
> > 
> > 大佬飞桨群人满了加不进去
> > 没用的，群里就几个技术人员，我们这些小问题，基本上不会帮我们解决，我加进去好久了，没效果，得自己找资料

群里每天都有同事在值班，包括周末，但可能信息太多被漏掉了，这种实际的工程问题查起来确实花时间，问题还存在的话你把模型打包贴上来（如果方便的话），具体是哪个安卓studio工程

**Comment by shiyuxin1999S** [comment]
> 

链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 
提取码：dp1u 
麻烦大佬帮忙看看

**Comment by mjp9527** [comment]
> > 
> 
> 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）

**Comment by shiyuxin1999S** [comment]
> > > 
> > 
> > 
> > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）

感谢感谢

**Comment by mjp9527** [comment]
> 另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理 public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢

这个可能需要您自己实现一下，ps: 多个框的问题还存在吗

**Comment by shiyuxin1999S** [comment]
> > > 
> > 
> > 
> > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）

![image](https://user-images.githubusercontent.com/44061194/173327772-35cb862d-0b1c-48ed-8fff-5a42c1da992b.png)
我看build里就是2.11rc版本，能否上传一下您修改后的版本

**Comment by jeekMic** [comment]
> > 另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理 public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢
> 
> 这个可能需要您自己实现一下，ps: 多个框的问题还存在吗
处理这种，public void onPreviewFrame(byte[] yuv) 数据的 有没有什么思路提供下呢，我那个可能也是跟上面版本不一致的问题 我先看下

**Comment by jeekMic** [comment]
> > > 另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理 public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢
> > 
> > 
> > 这个可能需要您自己实现一下，ps: 多个框的问题还存在吗
> > 对OpenGL和JNI不熟悉，看能不能提供点思路

**Comment by shiyuxin1999S** [comment]
> > > > 另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理 public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢
> > > 
> > > 
> > > 这个可能需要您自己实现一下，ps: 多个框的问题还存在吗
> > > 对OpenGL和JNI不熟悉，看能不能提供点思路

请问你的帧率大概有多少，我的只有不到10

**Comment by shiyuxin1999S** [comment]
> > > 
> > 
> > 
> > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）

这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了

**Comment by jeekMic** [comment]
> 

一样啊

**Comment by jeekMic** [comment]
> > > > > 另外我想问下，有没有实时处理处理相机帧回调的那种demo，我发现直接通过在java层处理照片，耗时比较高，但是那种纹理处理方式，我又用不了，有没有直接处理 public void onPreviewFrame(byte[] yuv) { } 这种回调数据的呢
> > > > 
> > > > 
> > > > 这个可能需要您自己实现一下，ps: 多个框的问题还存在吗
> > > > 对OpenGL和JNI不熟悉，看能不能提供点思路
> 
> 请问你的帧率大概有多少，我的只有不到10

你用哪种方式帧率不到10

**Comment by mjp9527** [comment]
> > > > 
> > > 
> > > 
> > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> 
> 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了

还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理

**Comment by shiyuxin1999S** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> > 
> > 
> > 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了
> 
> 还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理

编译的命令是./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_arm82_fp16=ON --with_opencl=ON --arch=armv8，然后导出模型的命令是paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl --optimize_out=picodet_s_416_coco_fp16_opencl --enable_fp16=true，把库和模型都换了，然后软件闪退，是不是--valid_targets应该=arm

**Comment by mjp9527** [comment]
转opencl模型：--valid_targets=opencl,arm   转arm: --valid_targets=arm

**Comment by mjp9527** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> > > 
> > > 
> > > 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了
> > 
> > 
> > 还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理
> 
> 编译的命令是./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_arm82_fp16=ON --with_opencl=ON --arch=armv8，然后导出模型的命令是paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl --optimize_out=picodet_s_416_coco_fp16_opencl --enable_fp16=true，把库和模型都换了，然后软件闪退，是不是--valid_targets应该=arm

手机确定支持fp16吧

**Comment by shiyuxin1999S** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > > > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > > > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> > > > 
> > > > 
> > > > 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了
> > > 
> > > 
> > > 还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理
> > 
> > 
> > 编译的命令是./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_arm82_fp16=ON --with_opencl=ON --arch=armv8，然后导出模型的命令是paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl --optimize_out=picodet_s_416_coco_fp16_opencl --enable_fp16=true，把库和模型都换了，然后软件闪退，是不是--valid_targets应该=arm
> 
> 手机确定支持fp16吧

应该支持吧，华为mate40pro。
[F  6/13 20: 8: 1.414 /island/Paddle-Lite/lite/core/kernel.cc GetInputDeclType:34] Check failed: type: no type registered for kernel [conv2d] input argument [SecondInput] with key conv2d/def
已放弃 (核心已转储)
转换模型的时候报这个错，不太懂，麻烦看看

**Comment by mjp9527** [comment]
> 



> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > > > > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > > > > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> > > > > 
> > > > > 
> > > > > 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了
> > > > 
> > > > 
> > > > 还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理
> > > 
> > > 
> > > 编译的命令是./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_arm82_fp16=ON --with_opencl=ON --arch=armv8，然后导出模型的命令是paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl --optimize_out=picodet_s_416_coco_fp16_opencl --enable_fp16=true，把库和模型都换了，然后软件闪退，是不是--valid_targets应该=arm
> > 
> > 
> > 手机确定支持fp16吧
> 
> 应该支持吧，华为mate40pro。 [F 6/13 20: 8: 1.414 /island/Paddle-Lite/lite/core/kernel.cc GetInputDeclType:34] Check failed: type: no type registered for kernel [conv2d] input argument [SecondInput] with key conv2d/def 已放弃 (核心已转储) 转换模型的时候报这个错，不太懂，麻烦看看

这个enable_fp16是针对cpu推理的，你可以分别试一下--valid_target=arm --enable_fp16=ON 和 --valid_target=opencl,arm

**Comment by shiyuxin1999S** [comment]
> > 
> 
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 链接：https://pan.baidu.com/s/1GESN4SrZohx22_ox-ZAb3Q?pwd=dp1u 提取码：dp1u 麻烦大佬帮忙看看
> > > > > > > > ![3381139D449994470C7C7E561](https://user-images.githubusercontent.com/54735487/173325450-6e35df71-4524-400a-9d6d-d037c09ab219.jpg)
> > > > > > > > 问题是库的版本，demo默认下载的是v2.10，但是你用的v2.11的opt转的模型，用v2.10的opt重新转一下模型，或者把库改成v2.11(修改库的话注意把build脚本中自动下载库的地方注释，以免覆盖）
> > > > > > 
> > > > > > 
> > > > > > 这个帧率只有不到10，请问有没有办法优化呢，比之前ncnn的那个版本差太多了
> > > > > 
> > > > > 
> > > > > 还无法识别的话ndk改成r20试一下，帧率提高有以下方法：1）string.xml线程数大于1；2）启用fp16推理（这个需要opt转模型时enable，然后预测库也要编译时with_arm82_fp16，同时手机支持armv8.2；3）使用opencl推理
> > > > 
> > > > 
> > > > 编译的命令是./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_arm82_fp16=ON --with_opencl=ON --arch=armv8，然后导出模型的命令是paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl --optimize_out=picodet_s_416_coco_fp16_opencl --enable_fp16=true，把库和模型都换了，然后软件闪退，是不是--valid_targets应该=arm
> > > 
> > > 
> > > 手机确定支持fp16吧
> > 
> > 
> > 应该支持吧，华为mate40pro。 [F 6/13 20: 8: 1.414 /island/Paddle-Lite/lite/core/kernel.cc GetInputDeclType:34] Check failed: type: no type registered for kernel [conv2d] input argument [SecondInput] with key conv2d/def 已放弃 (核心已转储) 转换模型的时候报这个错，不太懂，麻烦看看
> 
> 这个enable_fp16是针对cpu推理的，你可以分别试一下--valid_target=arm --enable_fp16=ON 和 --valid_target=opencl,arm

--valid_target=arm --enable_fp16=ON帧率大概是20，--valid_target=opencl,arm闪退
