### ISSUE TITLE
iOS ppocr_demo opt vs Paddle-Lite 版本不一致

### ISSUE THREAD

**Issue by greenhaixia** [PaddlePaddle/Paddle-Lite-Demo#278]
warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:v2.10-rc
      version of current Paddle-Lite:37558171c

请问这个该怎么解决？

**Comment by mjp9527** [comment]
这个没有影响，只是提示你opt是v2.10rc，PaddleLite当前库所用的commit是37558171c

**Comment by greenhaixia** [comment]
但是启动的时候直接在Run() 方法闪退了

**Comment by mjp9527** [comment]
运行libs下面的download.sh会自动下载编译好的库，用的是repo下的原始模型吗

**Comment by greenhaixia** [comment]
用的是工程下的prepare.sh生成的

**Comment by mjp9527** [comment]
prepare.sh都是拷贝预编译的库和官方模型，具体是哪个demo出错，手机机型是啥，ios还是安卓

**Comment by greenhaixia** [comment]
模型是用的工程下的prepare.sh脚本下载的

**Comment by SuperReally** [comment]
> 但是启动的时候直接在Run() 方法闪退了
我也是遇到个问题，拷贝PP-OCRv4_mobile_det.nb等文件到asset中（官方给的是ch_ppocr_mobile_v2.0_det_slim_opt.nb等，但是down.sh 下载的又不是这个，然后我改名成ch_ppocr_mobile_v2.0__slim_opt），ios运行的时候在run这个地方报错
