### ISSUE TITLE
Demo提供的yolov5n结构与官方yolov5n不同，导致替换后出现闪退，应该怎样解决？

### ISSUE THREAD

**Issue by Shainingu** [PaddlePaddle/Paddle-Lite-Demo#279]
主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。
我应该修改后处理过程吗？是否有参考的文档？
demo提供的模型又是怎样生成的？裁剪？
![image](https://user-images.githubusercontent.com/58648412/173307916-1e67eb9b-2008-41c9-bc86-d817ffc8ec39.png)
![image](https://user-images.githubusercontent.com/58648412/173307936-1989bd1b-c7cd-4c1f-ab83-b228697f19ee.png)

**Comment by mjp9527** [comment]
您好，官方模型是从哪个链接获取的

**Comment by Shainingu** [comment]
> 您好，官方模型是从哪个链接获取的

https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5n.pt

**Comment by Shainingu** [comment]
> 您好，官方模型是从哪个链接获取的

获取的pytorch模型通过yolov5项目导出为onnx，然后使用x2paddle转换为paddle lite模型

**Comment by mjp9527** [comment]
> > 您好，官方模型是从哪个链接获取的
> 
> 获取的pytorch模型通过yolov5项目导出为onnx，然后使用x2paddle转换为paddle lite模型

我们的模型是通过套件提供的，如果是输出tensor个数不一样的话需要修改后处理函数postprocess，可以参考readme文档：https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/yolov5n_detection_demo

**Comment by dium6i** [comment]
> 主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。 我应该修改后处理过程吗？是否有参考的文档？ demo提供的模型又是怎样生成的？裁剪？ ![image](https://user-images.githubusercontent.com/58648412/173307916-1e67eb9b-2008-41c9-bc86-d817ffc8ec39.png) ![image](https://user-images.githubusercontent.com/58648412/173307936-1989bd1b-c7cd-4c1f-ab83-b228697f19ee.png)

您好，想了解下这是什么软件？

**Comment by mjp9527** [comment]
> > 主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。 我应该修改后处理过程吗？是否有参考的文档？ demo提供的模型又是怎样生成的？裁剪？ ![image](https://user-images.githubusercontent.com/58648412/173307916-1e67eb9b-2008-41c9-bc86-d817ffc8ec39.png) ![image](https://user-images.githubusercontent.com/58648412/173307936-1989bd1b-c7cd-4c1f-ab83-b228697f19ee.png)
> 
> 您好，想了解下这是什么软件？

netron，可视化模型工具

**Comment by dium6i** [comment]
> 

感谢

**Comment by dium6i** [comment]
> 

感谢

**Comment by dium6i** [comment]
> > > 主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。 我应该修改后处理过程吗？是否有参考的文档？ demo提供的模型又是怎样生成的？裁剪？
> > 
> > 
> > 您好，想了解下这是什么软件？
> 
> netron，可视化模型工具

感谢

**Comment by Eric-is-good** [comment]
我遇到了一样的问题，请问是在 pipeline 里面怎么改

**Comment by Eric-is-good** [comment]
> > > 您好，官方模型是从哪个链接获取的
> > 
> > 
> > 获取的pytorch模型通过yolov5项目导出为onnx，然后使用x2paddle转换为paddle lite模型
> 
> 我们的模型是通过套件提供的，如果是输出tensor个数不一样的话需要修改后处理函数postprocess，可以参考readme文档：https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/yolov5n_detection_demo

请问一下这个后处理修改时怎么有什么调试方法，有没有方法在 c++ 里面打印输出，使错误或者矩阵大小让我看到

**Comment by Eric-is-good** [comment]
> 主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。 我应该修改后处理过程吗？是否有参考的文档？ demo提供的模型又是怎样生成的？裁剪？ ![image](https://user-images.githubusercontent.com/58648412/173307916-1e67eb9b-2008-41c9-bc86-d817ffc8ec39.png) ![image](https://user-images.githubusercontent.com/58648412/173307936-1989bd1b-c7cd-4c1f-ab83-b228697f19ee.png)

可以参照 https://github.com/Eric-is-good/yolov5_with_paddlelite

**Comment by Eric-is-good** [comment]
> > > 主要是输出的数量不同，下图分别是demo和官方提供的yolov5n。 我应该修改后处理过程吗？是否有参考的文档？ demo提供的模型又是怎样生成的？裁剪？ ![image](https://user-images.githubusercontent.com/58648412/173307916-1e67eb9b-2008-41c9-bc86-d817ffc8ec39.png) ![image](https://user-images.githubusercontent.com/58648412/173307936-1989bd1b-c7cd-4c1f-ab83-b228697f19ee.png)
> > 
> > 
> > 您好，想了解下这是什么软件？
> 
> netron，可视化模型工具

我解决了
可以参照 https://github.com/Eric-is-good/yolov5_with_paddlelite

**Comment by ggfine** [comment]
> > > 您好，官方模型是从哪个链接获取的
> > 
> > 
> > 获取的pytorch模型通过yolov5项目导出为onnx，然后使用x2paddle转换为paddle lite模型
> 
> 我们的模型是通过套件提供的，如果是输出tensor个数不一样的话需要修改后处理函数postprocess，可以参考readme文档：https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/yolov5n_detection_demo

仅修改postprecess可以么？preprocess要不要改？我的模型用x2paddle转换后是这样的：

![无标题](https://github.com/PaddlePaddle/Paddle-Lite-Demo/assets/56782230/9b133800-ef0b-4053-87e6-8900cf233f00)
