### ISSUE TITLE
.nb文件怎么转换得到的?

### ISSUE THREAD

**Issue by luoduo21** [PaddlePaddle/Paddle-Lite-Demo#28]
是从inference_model和model_with_code中的文件转换得到的吗?

**Comment by MARMOTatZJU** [comment]
借楼再问一个问题，我看到 _mobilenet_v1_for_cpu_ 和 _mobilenet_v1_for_npu_ 中的模型大小是不一样的，因此判定是不同的文件，需要不同的转换。请问model_optimize_tool如何转换得到npu使用的模型？

**Comment by MARMOTatZJU** [comment]
@luoduo21  参见 [模型转化方法](https://paddlepaddle.github.io/Paddle-Lite/v2.0.0/model_optimize_tool/)，需要从常规paddle模型转换得到
