### ISSUE TITLE
huawei mate40pro opencl推理的demo闪退

### ISSUE THREAD

**Issue by shiyuxin1999S** [PaddlePaddle/Paddle-Lite-Demo#280]
编译命令为：./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_opencl=ON --arch=armv8
opt命令为：paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl,arm --optimize_out=picodet_s_416_coco_fp32_opencl
demo为：picodet_detection_demo
已经将inference_lite_lib.android.armv8.opencl/cxx/include、inference_lite_lib.android.armv8.opencl/cxx/lib/libpaddle_light_api_shared.so替换PaddleLite/cxx/include、PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so
将inference_lite_lib.android.armv8.opencl/java/jar/PaddlePredictor.jar、inference_lite_lib.android.armv8.opencl/java/so/libpaddle_lite_jni.so替换PaddleLite/java/PaddlePredictor.jar、PaddleLite/java/libs/arm64-v8a/libpaddle_lite_jni.so
然后软件安装后启动会闪退
是不是inference_lite_lib.android.armv8.opencl/opencl/cl_kernel中的文件也需要替换，麻烦解答一下

**Comment by mjp9527** [comment]
> 编译命令为：./lite/tools/build_android.sh --toolchain=clang --with_cv=ON --with_extra=ON --with_opencl=ON --arch=armv8 opt命令为：paddle_lite_opt --model_dir=output_inference/picodet_s_416_coco_lcnet --valid_targets=opencl,arm --optimize_out=picodet_s_416_coco_fp32_opencl demo为：picodet_detection_demo 已经将inference_lite_lib.android.armv8.opencl/cxx/include、inference_lite_lib.android.armv8.opencl/cxx/lib/libpaddle_light_api_shared.so替换PaddleLite/cxx/include、PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so 将inference_lite_lib.android.armv8.opencl/java/jar/PaddlePredictor.jar、inference_lite_lib.android.armv8.opencl/java/so/libpaddle_lite_jni.so替换PaddleLite/java/PaddlePredictor.jar、PaddleLite/java/libs/arm64-v8a/libpaddle_lite_jni.so 然后软件安装后启动会闪退 是不是inference_lite_lib.android.armv8.opencl/opencl/cl_kernel中的文件也需要替换，麻烦解答一下

我看了一下，这个demo工程目前仅对cpu模型进行了适配

**Comment by sprouteer** [comment]
inference_lite_lib.android.armv8.opencl/opencl/cl_kernel中的文件不需要替换，建议编译的时候把log打开，
./lite/tools/build_android.sh --arch=armv8 --toolchain=clang --with_log=ON --with_extra=ON --with_cv=ON --with_opencl=ON
然后抓一下具体的log看看

**Comment by shiyuxin1999S** [comment]
> inference_lite_lib.android.armv8.opencl/opencl/cl_kernel中的文件不需要替换，建议编译的时候把log打开， ./lite/tools/build_android.sh --arch=armv8 --toolchain=clang --with_log=ON --with_extra=ON --with_cv=ON --with_opencl=ON 然后抓一下具体的log看看

A/Paddle-Lite: [F  6/18 18:42: 6.401 ...e/kernels/opencl/matmul_image_compute.cc:342 ReInitWhenNeeded] unsupported input case.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16676 (GLThread 2965), pid 16094 (o.ssd_detection)

这是手机连接Android studio的报错信息，我用docker环境重新编译了一次，这回库的问题应该可以排除了

**Comment by mjp9527** [comment]
> > inference_lite_lib.android.armv8.opencl/opencl/cl_kernel中的文件不需要替换，建议编译的时候把log打开， ./lite/tools/build_android.sh --arch=armv8 --toolchain=clang --with_log=ON --with_extra=ON --with_cv=ON --with_opencl=ON 然后抓一下具体的log看看
> 
> A/Paddle-Lite: [F 6/18 18:42: 6.401 ...e/kernels/opencl/matmul_image_compute.cc:342 ReInitWhenNeeded] unsupported input case. A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16676 (GLThread 2965), pid 16094 (o.ssd_detection)
> 
> 这是手机连接Android studio的报错信息，我用docker环境重新编译了一次，这回库的问题应该可以排除了

这个模型可能目前不支持，需要后期适配，先用cpu吧
