### ISSUE TITLE
编译运行后选择GPU模型闪退&模型极限推理性能如何？

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/Paddle-Lite-Demo#281]
按照教程：https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/yolov5n_detection_demo 在小米6上安装后，选择GPU模型会闪退，使用默认CPU模型推理的时候只有8fps，设置CPU thread num为8后最高15fps（设备老旧可以理解）。

在Android Studio中编译出apk文件后，使用小米11运行，选择GPU模型依然会闪退，设置CPU thread num为8后，最高也才19fps。

作为对比，使用iPhone 8下载ultralytics的检测软件：https://apps.apple.com/us/app/ultralytics/id1583935240 使用同样的yolov5n模型，识别效果会好很多。（可能是调用了GPU？iPhone 8的CPU（A11）CPU、GPU性能均不如小米11（骁龙888））

Paddle-Lite如何调用GPU模型而不闪退呢？官方有没有试过模型最高达到过多少fps？

**Comment by mjp9527** [comment]
yolov5n使用gpu模型需要替换动态库为带with_opencl标签的库( https://paddle-lite.readthedocs.io/zh/release-v2.11/quick_start/release_lib.html  )，替换方法可以参考readme文档，string.xml中切换模型路径为gpu即可

**Comment by dium6i** [comment]
> yolov5n使用gpu模型需要替换动态库为带with_opencl标签的库( https://paddle-lite.readthedocs.io/zh/release-v2.11/quick_start/release_lib.html )，替换方法可以参考readme文档，string.xml中切换模型路径为gpu即可

十分感谢，换了GPU推理效果好很多了！
![111](https://user-images.githubusercontent.com/75460093/175439549-106fc2ac-7fe4-47fa-afb6-e55b1751bcbc.png)
