### ISSUE TITLE
非原生，在uvc相机上怎么使用

### ISSUE THREAD

**Issue by jeekMic** [PaddlePaddle/Paddle-Lite-Demo#282]
请教下，我用的是开发板，接了3个相机，但是因为不是走Android的Camera，因此无法通过Camera.open()打开相机，只能通过uvc，但是uvc没有纹理处理的方式，不知道怎么办，看看是否有比较好的解决方案。

**Comment by mjp9527** [comment]
这个可以在群里和群友多交流交流，我们这边主要设备是手机，没有这方面的开发经验
