### ISSUE TITLE
在android studio上面rebuild image_classification的安卓项目失败

### ISSUE THREAD

**Issue by JaHangirYin** [PaddlePaddle/Paddle-Lite-Demo#283]
报错如下，麻烦大佬帮忙看看
ld: error: found local symbol '_edata' in global part of symbol table in file ***/paddle/Paddle-Lite-Demo-develop/Paddle-Lite-Demo-develop/image_classification/android/app/cxx/image_classification/app/src/main/cpp/../../../PaddleLite/cxx/libs/arm64-v8a/libpaddle_light_api_shared.so

**Comment by mjp9527** [comment]
NDK换成r20试一试，安卓studio可以安装多个版本的ndk，设置local.properties 中 ndk.dir指向r20

**Comment by SunshineBread** [comment]
> NDK换成r20试一试，安卓studio可以安装多个版本的ndk，设置local.properties 中 ndk.dir指向r20

还是没有用呀。。
