### ISSUE TITLE
iOS  OCR demo 运行后报错

### ISSUE THREAD

**Issue by TheLittleBoy** [PaddlePaddle/Paddle-Lite-Demo#284]
开启相机，开启后置摄像头，开启视频/拍照
随便拍摄点什么，然后就报错了：

libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(4.5.4) /Volumes/build-storage/build/master_iOS-mac/opencv/modules/imgproc/src/imgwarp.cpp:3144: error: (-215:Assertion failed) _src.total() > 0 in function 'warpPerspective'

**Comment by mjp9527** [comment]
什么也没有改动，直接运行repo的示例吗

**Comment by TheLittleBoy** [comment]
是的！
测试机型： iPhone XR

**Comment by Danvae** [comment]
> 是的！ 测试机型： iPhone XR

请问你解决了吗？正碰到同样问题
