### ISSUE TITLE
iOS  OCR demo 摄像头的图像获取的检测框位置不准确

### ISSUE THREAD

**Issue by TheLittleBoy** [PaddlePaddle/Paddle-Lite-Demo#285]
app 刚启动的截图：
<img width="433" alt="image" src="https://user-images.githubusercontent.com/3365421/175270904-4c505aec-4a39-4820-81e4-94e91fc6bc03.png">

开启摄像头后的截图：
<img width="430" alt="image" src="https://user-images.githubusercontent.com/3365421/175271018-5eff86e5-4462-4e1c-b263-55ec53a98641.png">

为何会有如此差异呢？

**Comment by mjp9527** [comment]
这个有可能是摄像头解码的问题，也可能是模型的问题，你可以自己训练一个模型替换一下

**Comment by TheLittleBoy** [comment]
应该是解码的原因，静态图片识别的就很好
<img width="437" alt="image" src="https://user-images.githubusercontent.com/3365421/175469488-c2fb1c16-5372-4fad-bd51-e0c3c43ae4b2.png">

**Comment by lhyos** [comment]
iOS运行，内存不释放，一次静态拍照识别就500M。 3次就崩溃了，你们遇到没

**Comment by TheLittleBoy** [comment]
@lhyos 没有哦

**Comment by lhyos** [comment]
> @lhyos 没有哦

那楼主这种 识别框往右下角偏移呢？

**Comment by lhyos** [comment]
识别框往右下角偏移解决没？ 我也是如此

**Comment by TheLittleBoy** [comment]
@lhyos 早就不记得了
