### ISSUE TITLE
使用paddlelite 转换paddle模型时，选择--valid_targets=x86时出现This model is not supported, because 1 ops are not supported on 'x86'. These unsupported ops are: 'nearest_interp_v2'.错误

### ISSUE THREAD

**Issue by lw-2017** [PaddlePaddle/Paddle-Lite-Demo#286]
使用paddlelite 转换paddle模型时，选择--valid_targets=x86时出现This model is not supported, because 1 ops are not supported on 'x86'. These unsupported ops are: 'nearest_interp_v2'.错误

**Comment by chenjiaoAngel** [comment]
请问你使用的Paddle Lite 版本号是多少？
在最新release/v2.11版本上，x86平台已经支持nearest_interp_v2
