### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x70b8500000 in tid 22548 (GLThread 758), pid 22511 (o.ssd_detection)

### ISSUE THREAD

**Issue by solinL** [PaddlePaddle/Paddle-Lite-Demo#287]
demo地址：Paddle-Lite-Demo-develop\object_detection\android\app\cxx\picodet_detection_demo
模型文件：自己训练picodet_s_320_voc，opt导出model.nb，opt版本v2.10
修改demo文件：
1.预测库替换为v2.10
2.Pipeline.cc修改66行为单输入

**Comment by solinL** [comment]
![lALPGT5jENtUEBbNBBjNB4g_1928_1048](https://user-images.githubusercontent.com/12882182/176425018-dde7910d-01eb-4ecb-83a6-919f6cab0edd.png)

**Comment by solinL** [comment]
![lQLPJxZy9SKbmhDNAgzNAYOw18F8TTGa-_oCvWmr0IAnAA_387_524](https://user-images.githubusercontent.com/12882182/176425136-846ca060-3208-4ac7-8bbd-78ffd24451d1.png)

**Comment by solinL** [comment]
![lALPGTdIE5H9ZebNBBjNB4g_1928_1048](https://user-images.githubusercontent.com/12882182/176425423-34459e4b-6048-44d8-af8b-e1c7f1c10105.png)

**Comment by mjp9527** [comment]
应该还是前后处理不对，具体的使用问题还是需要用户自己排查，可以依次检查输入shape、个数、数据类型；输出shape、个数、数据类型，OPT和库是否匹配，preprocess、postprocess是否考虑全面等

**Comment by QtyearLin** [comment]
同样的问题 但是java 同分支下 运行同一模型确正常
