### ISSUE TITLE
Why Demo much slower than official APK？

### ISSUE THREAD

**Issue by Wzj02200059** [PaddlePaddle/Paddle-Lite-Demo#288]
Thx for awesome repo.
I compare picodet_detection_demo to official PicoDet APK【https://paddledet.bj.bcebos.com/deploy/third_engine/PP-PicoDet.apk】 on my XiaoMi12 Phone。
picodet_detection_demo could only achieve 20 Fps，and PicoDet APK could achieve 100Fps。
I use same setting， and same picodet_s_416 model。Why the performance gap is so huge?
If i want to promote this demo to 100Fps，What should i do？
Really looking forward to yours reply！

**Comment by baihaozi12** [comment]
My porsche also have same problem. I mean my huawei porsche design mate 40 rs 5G.

**Comment by mjp9527** [comment]
where did you find "PicoDet APK" or this link?

**Comment by Wzj02200059** [comment]
> where did you find "PicoDet APK" or this link?

![image](https://user-images.githubusercontent.com/32172413/177264960-9fdfe8fc-a812-4fb1-8231-f29ac2c02e46.png)
https://paddledet.bj.bcebos.com/deploy/third_engine/PP-PicoDet.apk

**Comment by mjp9527** [comment]
There are many reasons affecting efficiency， such as cpu threads num, opencl instead of cpu, fp16 or int8. Are you sure picodet_s_416 model is same, not only the input shape but also the whole network structure？

**Comment by Wzj02200059** [comment]
> There are many reasons affecting efficiency， such as cpu threads num, opencl instead of cpu, fp16 or int8. Are you sure picodet_s_416 model is same, not only the input shape but also the whole network structure？
I don't know the detail of Official APK.
But my demo if 4 threds and fp16。
the model is pretty fast, and the sum of picodet_detection_demo‘s Predict time + Preprocess time + Postprocess time is 20ms. 
![1657076823605](https://user-images.githubusercontent.com/32172413/177459481-4917f78e-6d8d-4e21-8b0d-119e97e0f02e.png)
Its doesn't seem to be model’s problem, I want to know is there some limit lead to low frame rate，maybe camera or some limit？

**Comment by mjp9527** [comment]
> > There are many reasons affecting efficiency， such as cpu threads num, opencl instead of cpu, fp16 or int8. Are you sure picodet_s_416 model is same, not only the input shape but also the whole network structure？
> > I don't know the detail of Official APK.
> > But my demo if 4 threds and fp16。
> > the model is pretty fast, and the sum of picodet_detection_demo‘s Predict time + Preprocess time + Postprocess time is 20ms.
> > ![1657076823605](https://user-images.githubusercontent.com/32172413/177459481-4917f78e-6d8d-4e21-8b0d-119e97e0f02e.png)
> > Its doesn't seem to be model’s problem, I want to know is there some limit lead to low frame rate，maybe camera or some limit？

CPU 4-threads and fp16 quant is the reason why apk is faster than paddle-lite-demo.
first, paddle-lite-demo is 1-thread default and you can set it to 4.
second,  paddle-lite-demo 's model precision is float.
