### ISSUE TITLE
no enough for mallocing 4294946096 bytes

### ISSUE THREAD

**Issue by thefoolend** [PaddlePaddle/Paddle-Lite-Demo#290]
How to deal with this error after putting the data into the model and running

A/Paddle-Lite: [F  7/11 10:10:40.259 ...ite/lite/backends/host/target_wrapper.cc:29 Malloc] Check failed: p: Error occurred in TargetWrapper::Malloc period: no enough for mallocing 4294946096 bytes.
A/libc: /Volumes/Android/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F  7/11 10:10:40.259 ...ite/lite/backends/host/target_wrapper.cc:29 Malloc] Check failed: p: Error occurred in TargetWrapper::Malloc period: no enough for mallocing 4294946096 bytes.
    " failed
    Fatal signal 6 (SIGABRT), code -6 in tid 12030 (Predictor Worke)

**Comment by thefoolend** [comment]
Call on Android platform paddlelite model（.nb）

**Comment by thefoolend** [comment]
for (int i = 0; i < warmupIterNum; i++) {
            paddlePredictor.run();
        }

**Comment by mjp9527** [comment]
which demo?

**Comment by thefoolend** [comment]
object_detection_demo

**Comment by thefoolend** [comment]
object_detection_demo

**Comment by thefoolend** [comment]
> which demo?
object_detection_demo

**Comment by thefoolend** [comment]
> which demo?

object_detection_demo

**Comment by mjp9527** [comment]
Hello，can you provide more detailed information,  as follows:
1) Are you running the official native model?  if you have changed the model,  You can refer to the readme.md.
if you get the same error, give me the model.
2) Specific phone model， which manufacturer?
3) object_det_demo has 4 branchs, which one? shell or app? if you run the android app and get this error, you can try shell demo.

**Comment by thefoolend** [comment]
> Hello，can you provide more detailed information, as follows:
> 
> 1. Are you running the official native model?  if you have changed the model,  You can refer to the readme.md.
>    if you get the same error, give me the model.
> 2. Specific phone model， which manufacturer?
> 3. object_det_demo has 4 branchs, which one? shell or app? if you run the android app and get this error, you can try shell demo.
1. I have changed the model
2. Phone mode：BMH-AN10. Manufacturer:huawei
model [link](链接：https://pan.baidu.com/s/1uuDPQaJvN4o1iAp5I58KSg?pwd=xr24 
提取码：xr24)

**Comment by thefoolend** [comment]
app

**Comment by mjp9527** [comment]
> app

[ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo，this

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?



> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo， this one

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo，this one.
I use my model and my input data but can't run. Loading the model can, but it can't make the model run

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo，   this one.
I use my model and my input data but can't run. Loading the model can, but it can't make the model run

**Comment by thefoolend** [comment]
> > app
> 
> [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo,        this one.
I use my model and my input data but can't run. Loading the model can, but it can't make the model run.

**Comment by mjp9527** [comment]
> > > app
> > 
> > 
> > [ssd_mobilenetv1_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx/ssd_mobilenetv1_detection_demo)，this one?
> 
> https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo, this one. I use my model and my input data but can't run. Loading the model can, but it can't make the model run.

Please checkout the develop branch and git pull the new commit. The master branch is no longer maintained.
https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/android/app/cxx
