### ISSUE TITLE
PP-ShiTU 的android demo 中替换自己转换的模型跑不起来

### ISSUE THREAD

**Issue by hyouyan** [PaddlePaddle/Paddle-Lite-Demo#291]
直接下载下来的 模型文件：
1：  wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar
2：通过paddle-lite转化（paddle_lite_opt  --model_file=picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer/inference.pdmodel --param_file=picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer/inference.pdiparams --valid_targets=arm --optimize_out=model_picodet_opt --quant_model=true --quant_type=QUANT_INT16）
3：放到shitu的android demo，直接跑，应用会崩溃
4：崩溃的log如下：
2 16:46:07.576 E/libc++abi(27858): terminating with uncaught exception of type std::exception: std::exception
07-12 16:46:07.577 F/libc    (27858): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27925 (Predictor Worke), pid 27858 (e.demo.pp_shitu)
07-12 16:46:07.770 I/crash_dump64(27962): obtaining output fd from tombstoned, type: kDebuggerdTombstone
07-12 16:46:07.775 I/tombstoned(  713): received crash request for pid 27925
07-12 16:46:07.781 I/crash_dump64(27962): performing dump of process 27858 (target tid = 27925)
07-12 16:46:07.785 F/DEBUG   (27962): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-12 16:46:07.785 F/DEBUG   (27962): Build fingerprint: 'Xiaomi/raphael/raphael:11/RKQ1.200826.002/V12.5.6.0.RFKCNXM:user/release-keys'
07-12 16:46:07.785 F/DEBUG   (27962): Revision: '0'
07-12 16:46:07.785 F/DEBUG   (27962): ABI: 'arm64'
07-12 16:46:07.808 F/DEBUG   (27962): Timestamp: 2022-07-12 16:46:07+0800
07-12 16:46:07.808 F/DEBUG   (27962): pid: 27858, tid: 27925, name: Predictor Worke  >>> com.baidu.paddle.lite.demo.pp_shitu <<<
07-12 16:46:07.808 F/DEBUG   (27962): uid: 10350
07-12 16:46:07.808 F/DEBUG   (27962): signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
07-12 16:46:07.808 F/DEBUG   (27962): Abort message: 'terminating with uncaught exception of type std::exception: std::exception'
07-12 16:46:07.808 F/DEBUG   (27962):     x0  0000000000000000  x1  0000000000006d15  x2  0000000000000006  x3  0000007b05965e50
07-12 16:46:07.808 F/DEBUG   (27962):     x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
07-12 16:46:07.808 F/DEBUG   (27962):     x8  00000000000000f0  x9  d3ee3521c260198e  x10 0000000000000000  x11 ffffffc0fffffbdf
07-12 16:46:07.808 F/DEBUG   (27962):     x12 0000000000000001  x13 0000000062cd34cf  x14 00219083dfa15959  x15 0000cc83c0e95b97
07-12 16:46:07.808 F/DEBUG   (27962):     x16 0000007bf4698948  x17 0000007bf4675490  x18 0000000000000000  x19 0000000000006cd2
07-12 16:46:07.808 F/DEBUG   (27962):     x20 0000000000006d15  x21 00000000ffffffff  x22 00000000ffffff80  x23 00000000ffffffc8
07-12 16:46:07.808 F/DEBUG   (27962):     x24 0000007b059660b0  x25 0000007b05965f80  x26 0000007b05965fc0  x27 0000000000000000
07-12 16:46:07.808 F/DEBUG   (27962):     x28 0000007b059677a0  x29 0000007b05965ed0
07-12 16:46:07.808 F/DEBUG   (27962):     lr  0000007bf4624cf8  sp  0000007b05965e30  pc  0000007bf4624d24  pst 0000000000000000
07-12 16:46:07.812 F/DEBUG   (27962): backtrace:
07-12 16:46:07.812 F/DEBUG   (27962):       #00 pc 000000000008cd24  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: d2bad1502ac7810a2cce958ef2191244)
07-12 16:46:07.812 F/DEBUG   (27962):       #01 pc 0000000000412738  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #02 pc 0000000000412898  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #03 pc 000000000040f6bc  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #04 pc 000000000040ede0  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #05 pc 000000000040ed60  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (__cxa_throw+120) (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #06 pc 00000000002a683c  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #07 pc 00000000003b62c0  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #08 pc 00000000003b6204  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (paddle::lite::RuntimeProgram::Run()+52) (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #09 pc 00000000003c3b4c  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libpaddle_light_api_shared.so (BuildId: f9edc7993c1c57d2d4608783d535ae69214fc6fe)
07-12 16:46:07.812 F/DEBUG   (27962):       #10 pc 00000000000973e8  /data/app/~~jKBvhRFB7kToIrLOw00ojg==/com.baidu.paddle.lite.demo.pp_shitu-KtsCvAFupuuykFj1NRUnpA==/lib/arm64/libNative.so (BuildId: 943645aaa0bb76eefe1e3315473b3e25a6f99b36)

**Comment by hyouyan** [comment]
是我哪边还需要配置吗？

**Comment by mjp9527** [comment]
参考readme文档

**Comment by hyouyan** [comment]
> 参考readme文档
源代码里面用的模型，输入参数只有图片
![015bd7d49b68aaf425e0f4bd1ef360d](https://user-images.githubusercontent.com/49305680/178700394-818fe71a-493d-444f-9fa5-446e5f473f62.png)
但是我wget 下来的模型转换成lite模型后，输入不一样，请问是什么原因吗？

![940ee74ab47699072ccf6af22d4f080](https://user-images.githubusercontent.com/49305680/178700653-7568e0eb-5558-47b5-9d5b-23370e9b23aa.png)

**Comment by mjp9527** [comment]
PPshitu是参考了PPClas repo，你这个模型是从哪获取的

**Comment by hyouyan** [comment]
> wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar

这个链接获取的

**Comment by mjp9527** [comment]
> > wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar
> 
> 这个链接获取的

模型输入输出不一样，需要修改前后处理，可以参考下readme文档

**Comment by mjp9527** [comment]
原模型来自PaddleClas

**Comment by hyouyan** [comment]
> > > wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar
> > 
> > 
> > 这个链接获取的
> 
> 模型输入输出不一样，需要修改前后处理，可以参考下readme文档

怎么样才能生成一样的模型文件？
