### ISSUE TITLE
PicoDet的Demo是不是无法使用GPU？

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/Paddle-Lite-Demo#292]
我使用PicoDet的Demo替换自己的模型（PicoDet-L-640）成功在手机上运行，就是太卡了（毕竟Demo用的S，我用的L）。

之前跑Yolov5n的Demo可以用OpenCL的预测库替换，就可以使用GPU了。

PicoDet的Demo我照着替换了一下，运行不起来了，是不是暂时还不支持使用GPU呢？

**Comment by mjp9527** [comment]
模型和预测库都替换了吗

**Comment by dium6i** [comment]
> 模型和预测库都替换了吗

模型替换了自己训练的，在CPU下可以跑，替换了opencl的预测库后就打不开了。

**Comment by mjp9527** [comment]
> > 模型和预测库都替换了吗
> 
> 模型替换了自己训练的，在CPU下可以跑，替换了opencl的预测库后就打不开了。

模型也需要使用opencl的，--valid_targets=opencl,arm

**Comment by dium6i** [comment]
> > > 模型和预测库都替换了吗
> > 
> > 
> > 模型替换了自己训练的，在CPU下可以跑，替换了opencl的预测库后就打不开了。
> 
> 模型也需要使用opencl的，--valid_targets=opencl,arm

好的，了解了，我试试看。之前GPU能跑通的yolov5n重新来了一遍也跑不通了，不知道是不是我自己的环境问题，我搞一下，如有问题再问您。
