### ISSUE TITLE
Shitu的android demo中，特征索引(index)在哪呢？

### ISSUE THREAD

**Issue by hyouyan** [PaddlePaddle/Paddle-Lite-Demo#293]
大佬好！针对shitu的android demo，我有如下几个问题，希望大佬百忙之中帮忙告知我：
1：Shitu的android demo中，特征索引(index)在哪块代码实现呢？
2：如果已经在服务器针对自己的样本训练完后，我要如何更新android demo里面的索引(index)
2：服务器训练完后，我要如何更新android demo中的label.txt

谢谢！！！

**Comment by hyouyan** [comment]
android demo里向量检索这步是怎么实现的呢？

**Comment by mjp9527** [comment]
index是指？ label更新参考对应文件夹下的readme文档

**Comment by hyouyan** [comment]
> index是指？ label更新参考对应文件夹下的readme文档
在服务器的项目中，有一个步骤是建立索引库：
python python/build_gallery.py \
    -c configs/build_general.yaml \
    -o IndexProcess.data_file="/home/aistudio/dataset/gallery_update.txt" \
    -o IndexProcess.index_dir="/home/aistudio/dataset/index_update"
特征提取完后，在索引库中，用向量检索识别出图片。
python python/predict_system.py \
    -c configs/inference_general.yaml \
    -o Global.infer_imgs="/home/aistudio/dataset/test_image/recognition_2.jpg" \
    -o IndexProcess.index_dir="/home/aistudio/dataset/index_update"

android 的demo中没有看到指定index_dir的路径。

**Comment by hyouyan** [comment]
android 的demo，是不是直接用PPLCNet_x2_5做图片多分类，没有采用索引的方式？
如果是的话，我想采用索引的方式，有没有可参考的案例进行移植？谢谢！！！

**Comment by jaunce** [comment]
怎么样更新检索库？
