### ISSUE TITLE
How to get optimized model for running on NPU

### ISSUE THREAD

**Issue by MARMOTatZJU** [PaddlePaddle/Paddle-Lite-Demo#30]
From the demo [Paddle-Lite-Demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/) , I found that [mobilenet_v1_for_cpu](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/app/src/main/assets/image_classification/models/mobilenet_v1_for_cpu) and [mobilenet_v1_for_npu](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/app/src/main/assets/image_classification/models/mobilenet_v1_for_npu) have different size, so I suppose that they are not the same model.

However, from the description for [model_optimize_tool](https://paddlepaddle.github.io/Paddle-Lite/v2.0.0/model_optimize_tool/), I did not get the related information, thus I am not sure whether the optimized model generated by mode_optimize_tool is for CPU or NPU.

More concretely, I am interested in the method to generate the model for running on NPU. Could you provide a solution to this need? Thanks in advance.

**Comment by zhupengyang** [comment]
- npu的模型优化依赖于华为的hiai，所以是不能在x86上用model_optimize_tool优化的
- model_optimize_tool也没有针对npu的优化选项
- 使用开启npu相关编译选项的full_publish库，可以跑paddle的原始模型；之后可以调用相关接口保存出优化后的npu模型；再之后就可以用tiny_publish的库去跑优化后的npu模型

**Comment by hong19860320** [comment]
下一个版本的model_optimize_tool支持x86平台上生成NPU的模型
