### ISSUE TITLE
运行性能参数分析 & 部分Demo运行问题

### ISSUE THREAD

**Issue by Liliyaw** [PaddlePaddle/Paddle-Lite-Demo#300]
Hi There, 谢谢帮忙解答。
目前在RPI4上跑Develop分支中Paddle-Lite-Demo里的demo遇到一些问题想要咨询。
1) 想了解一下运行结果中的一些性能参数例如: prediction time, preprocess time 等是否准确, 是如何计算的, 是否可以反映算法性能, 如何与其他的对比? 
2) 目前尝试过的图像分类以及目标检测的demo中都存在一些open cv中变量函数定义的问题，例如：CV_CAP_PROP_FRAME_WIDTH > cv::CAP_PROP_FRAME_WIDTH, CV_BGRA2RGB > cv::COLOR_BGRA2RGB才能正常运行, 目标检测里面还有一个其他的算子报错提示: std::ifstream file' has incomplete type and cannot be defined, 没找到如何更改的方法。
3) 目前的图像分类Top前2的置信度很接近, 是否和模型有关?
<img width="532" alt="image" src="https://user-images.githubusercontent.com/94680624/183573820-531237bb-d647-4097-afee-45de7247b0c4.png">

**Comment by mjp9527** [comment]
1. 前后处理只跑了一次，测得的耗时偏大，预测耗时可以通过修改pipeline.h里的repeat_和warmup_跑多次，计算方法就是求平均值，默认只跑一次，耗时偏大。
2. cv::CAP或者CV_CAP是Opencv4.x不兼容之前的写法，"算子报错提示std::ifstream file' has incomplete type and cannot be defined" 这个是啥意思，具体哪个算子，log信息可以多贴一些。
3. 精度结果和模型有关
