### ISSUE TITLE
picodet_demo ios 15.5 无法打开直接闪退 Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by omegamt** [PaddlePaddle/Paddle-Lite-Demo#302]
尝试过  v2.10 v2.11 自行编译的develop版本 Paddle-Lite都没有解决

<img width="1432" alt="WX20220811-190520@2x" src="https://user-images.githubusercontent.com/24944112/184120021-5e813343-79bc-4605-ae9e-51e39215a27d.png">

**Comment by omegamt** [comment]
编译全量预测库设置为ON时,问题解决了

```
./lite/tools/build.sh \
  --arm_os=ios64 \
  --arm_abi=armv8 \
  --build_extra=ON \
  ios

```

**Comment by AndSonder** [comment]
> 编译全量预测库设置为ON时,问题解决了
> 
> ```
> ./lite/tools/build.sh \
>   --arm_os=ios64 \
>   --arm_abi=armv8 \
>   --build_extra=ON \
>   ios
> ```

请问您这个是在哪里修改的呢 @omegamt

**Comment by omegamt** [comment]
@AndSonder  源码编译Paddle-lite 库的命令

**Comment by AndSonder** [comment]
> @AndSonder 源码编译Paddle-lite 库的命令

请问您是直接把编译生成的 include 和 lib 文件替换了 工程目录下的include 和 lib吗 @omegamt 

我替换了之后还是有下面的报错：

load image failed
2022-08-17 20:10:59.830297+0800 face_keypoints_detection[35003:2615422] camera available: YES
not implemented, set to default 4GB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1118 Setup] ARM multiprocessors name: Apple
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1119 Setup] ARM multiprocessors number: 6
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 0, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 1, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 2, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 3, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 4, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 5, max freq: 1000000, min freq: 1000000, cluster ID: 0, CPU ARCH: A0
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1127 Setup] L1 DataCache size is: 
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 64 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1131 Setup] L2 Cache size is: 
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 2048 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1135 Setup] L3 Cache size is: 
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  8/17 20:10:59.830 ...ads/Paddle-Lite/lite/core/device_info.cc:1139 Setup] Total memory: 4194304KB
[F  8/17 20:10:59.830 ...s/Paddle-Lite/lite/core/model/base/io.cc:46 BinaryFileReader] Check failed: file_: Unable to open file: /private/var/containers/Bundle/Application/C399126B-E90D-40CA-B6AE-145295894B5E/face_keypoints_detection.app/third-party/assets/models/face_detection_for_cpu/model.nb
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
