### ISSUE TITLE
ppocr-demo 无法检测识别字符

### ISSUE THREAD

**Issue by qiulongquan** [PaddlePaddle/Paddle-Lite-Demo#306]
我按照ppocr-demo上面的说明在手机端安装了app但是启动app屏幕没有任何识别结果，没有检测框没有识别字符内容（如下图）
我没有收到任何错误信息，模型是默认提供的opt后的cls det rec模型，配置没有修改过
手机型号 samsung SM-N975C
我测试了另外一款app（face keypoints detection）没有问题，有人可以给我一些建议吗？
![20220905122323](https://user-images.githubusercontent.com/36796264/188355086-dc1326a8-f383-473e-a863-158530da2023.jpg)

**Comment by qiulongquan** [comment]
我已经解决了这个问题，主要是模型路径不正确，没有正确加载模型
例子里面的实际路径是assert/model/ch_ppocr_mobile_v2.0_rec_slim_opt.nb,但是代码里面是ch_ppocr_mobile_v2.0_rec_slim_opt.nb，导致无法正确加载model，把所有的模型都放到assert目录下面重新build就可以了

**Comment by ppppppppyyyy** [comment]
您好，我也遇到了相同的问题，但是我没有看懂你的回答。原来模型就存放在assets/models下，请问哪里修改正确路径？

**Comment by dium6i** [comment]
按照你的方法成功检测到文本框了，可是就只有检测框也没有识别结果啊，你遇到过这样的情况么？
