### ISSUE TITLE
运行yolov3 mobilenet 出错

### ISSUE THREAD

**Issue by Kanon777** [PaddlePaddle/Paddle-Lite-Demo#31]
模型转换，用cxx运行正常，安卓demo预测过程报错

**Comment by AIpioneer** [comment]
您好，能否贴一下详细信息

**Comment by hong19860320** [comment]
已经提供 yolov3_mobilenetv3的demo https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/yolo_detection_demo
