### ISSUE TITLE
iOS接入paddle-Lite遇到Unknown type name 'MobileConfig问题导致项目无法运行

### ISSUE THREAD

**Issue by GGBoyIsHere** [PaddlePaddle/Paddle-Lite-Demo#311]
我使用iOS接入paddle-Lite，paddle_api.h中存在一个名为MobileConfig的Class ,我想引用它。

我在 https://github.com/PaddlePaddle/Paddle-Lite-Demo 中下载了原Demo，在使用其中的human_segmentation模块时能正常运行也能调用MobileConfig。我修改了原Demo的prepare.sh文件，并且在human_segmentation同一层级中创建了我的Demo —— FaceDemo001，并在Xcode->TARGETS->BuildSetting中配置了Library Search Paths、Other Linker Flags、Framework Search Paths和User Header Search Paths，结果我仅仅#include "include/paddle_api.h"时项目能正常运行，但使用MobileConfig创建对象时就报错“Unknown type name 'MobileConfig'; did you mean 'paddle::lite_api::MobileConfig'?”，可是我明明将Command+右键MobileConfig时能够跳转到paddle_api.h文件中的

![WX20221011-103650@2x](https://user-images.githubusercontent.com/92911169/195033254-826bafd0-a16f-459c-8165-ac3603b874f9.png)

![WX20221011-160421@2x](https://user-images.githubusercontent.com/92911169/195034043-5c4aea30-1989-42ed-86d4-4df8483c7f16.png)

**Comment by hong19860320** [comment]
从截图上看，你漏了这一行代码 https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/586b0d13757118f366ae22d88560acc6b4a0dd9f/human_segmentation/ios/human_segmentation/human_segmentation/ViewController.mm#L30

**Comment by GGBoyIsHere** [comment]
> 从截图上看，你漏了这一行代码
> 
> https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/586b0d13757118f366ae22d88560acc6b4a0dd9f/human_segmentation/ios/human_segmentation/human_segmentation/ViewController.mm#L30


谢谢，你帮我解决了Unknown的问题。但是遇到了另外的问题：框架帮我将人物识别了出来，可我不知道如何把人物单独抠出来

![human2](https://user-images.githubusercontent.com/92911169/195062671-a9ade46a-2e42-4e64-8ccc-6ffd775fbc38.jpg)

**Comment by hong19860320** [comment]
如果是iOS ，建议到网上搜索下如何在iOS 使用OpenCV编辑图像，最简单的方法是对于区域外的像素点全部设置成一个颜色。

**Comment by GGBoyIsHere** [comment]
> 如果是iOS ，建议到网上搜索下如何在iOS 使用OpenCV编辑图像，最简单的方法是对于区域外的像素点全部设置成一个颜色。

我也想如此做，但是我不知道如何设置，事实上我甚至不清楚哪段代码中体现了人物区域

**Comment by hong19860320** [comment]
> > 如果是iOS ，建议到网上搜索下如何在iOS 使用OpenCV编辑图像，最简单的方法是对于区域外的像素点全部设置成一个颜色。
> 
> 我也想如此做，但是我不知道如何设置，事实上我甚至不清楚哪段代码中体现了人物区域

可以重点关注这段代码 https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/586b0d13757118f366ae22d88560acc6b4a0dd9f/human_segmentation/ios/human_segmentation/human_segmentation/ViewController.mm#L104
