### ISSUE TITLE
求一个能跑ppyolo tiny模型，输入图片，并能得到预测的结果（坐标和名称）的android demo？

### ISSUE THREAD

**Issue by simpsonyang** [PaddlePaddle/Paddle-Lite-Demo#314]
我下载了几个paddle lite demo, 但只要替换成我opt出来的nb文件，就都运行不了，实在搞不定了。求大神给一个现成的Android demo，可以运行ppyolo tiny模型，输入图片，能得到预测的结果（坐标和标签值），我拿到后只需要替换成我的模型就可以跑的。感谢了！

**Comment by OneCoser** [comment]
有没有可能是你的模型问题？或者你可以参考一下这个项目的做法：https://github.com/equationl/paddleocr4android

**Comment by simpsonyang** [comment]
> 有没有可能是你的模型问题？或者你可以参考一下这个项目的做法：https://github.com/equationl/paddleocr4android

感谢你的回复，我尝试过官方的demo，也参考了这个：https://github.com/ralph0813/Paddle_Lite_Object_Detection_Demo ，在后面这个demo中，我给它替换了2.11的so和jar以后，它也跑不起来，然后我用2.11的opt_linux优化生成我的nb文件，也还是不行。估计可能是模型和paddele lite库不匹配，但是具体解决方法就实在找不到了。

**Comment by simpsonyang** [comment]
又经过一番尝试，在输出里看到 in_dims.size() == 4 || in_dims.size() == 5 test error，网上搜索了一下，看到这篇issue：https://github.com/PaddlePaddle/Paddle-Lite/issues/7336，
于是我用netron查看我的nb文件，发现输入确实是3个，但是java代码里面 inputTensor确实少了，于是修改如下：
// Set input shape
        Tensor inputTensor1 = getInput(1);
        inputTensor1.resize(inputShape);
        Tensor sizeTensor = getInput(0);
        sizeTensor.resize(new long[] {1,2});
        Tensor scaleTensor = getInput(2);
        scaleTensor.resize(new long[] {1,2});
再运行，可以出来了，但是结果的坐标错误，debug跟踪一下outputTensor.getFloatData()，里面的值也确实不对，这里就又卡住了。
