### ISSUE TITLE
iOS Demo模型更新到OCRv3出现崩溃

### ISSUE THREAD

**Issue by yinqinggong** [PaddlePaddle/Paddle-Lite-Demo#322]
iOS Demo更新到V3模型，检测模型ch_PP-OCRv3_det_slim_infer.nb是OK的，但是识别模型(ch_PP-OCRv3_rec_slim_infer.nb)运行出现崩溃，位置在rec_process.cc文件的 predictor_->Run();处。
rec_image_shape{3, 32, 320}修改为rec_image_shape{3, 48, 320};后也是如此。
![image](https://user-images.githubusercontent.com/9996124/200246616-e936dd16-65da-4d3d-a090-6ddeb28d14b2.png)
![image](https://user-images.githubusercontent.com/9996124/200246698-5a1d098e-4488-4261-96ee-da607cf0476f.png)

**Comment by UnstoppableCurry** [comment]
paddlelite框架我不知道 v3 rec模型在ncnn上是不支持5D reshape等操作的需要对OP修改
