### ISSUE TITLE
android端ocr文字提取问题

### ISSUE THREAD

**Issue by LinhaiGu** [PaddlePaddle/Paddle-Lite-Demo#324]
demo中ios是可以获取文字内容并展示，但android demo只能框出文字，没有提取文字的代码

**Comment by wskwsy** [comment]
你好，文字提取解决了吗

**Comment by wskwsy** [comment]
> demo中ios是可以获取文字内容并展示，但android demo只能框出文字，没有提取文字的代码

你好，文字提取解决了吗
