### ISSUE TITLE
Paddle Lite 源码编译文档，现在文档不存在了

### ISSUE THREAD

**Issue by hqsh** [PaddlePaddle/Paddle-Lite-Demo#328]
在如下这个链接的文档中，又如下这句话，但是点进去发现文档不存在。能否帮忙看一下，文档放哪里了？感谢！

https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/ocr/android/app/cxx/ppocr_demo

参考 [Paddle Lite 源码编译文档](https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_env.html)，编译 Android 预测库

**Comment by litch-cl** [comment]
https://www.paddlepaddle.org.cn/lite/v2.11/demo_guides/huawei_ascend_npu.html 只有这个了
