### ISSUE TITLE
官方demo无法运行在高版本ndk上

### ISSUE THREAD

**Issue by whr18756973961** [PaddlePaddle/Paddle-Lite-Demo#334]
face_keypoints_detection demo 无法运行在高版本的demo上,报错
ld: error: found local symbol '_edata' in global part of symbol table in file 
![image](https://user-images.githubusercontent.com/14271446/209095678-e35f3d8d-425c-4fc4-a408-626549cfcddd.png)

**Comment by hqsh** [comment]
你好，你是用哪个版本？
