### ISSUE TITLE
当前demo，安卓10及一下运行正常，安卓11出现闪退问题

### ISSUE THREAD

**Issue by as7786971** [PaddlePaddle/Paddle-Lite-Demo#339]
![image](https://user-images.githubusercontent.com/47085862/216932175-dc5bb96b-f3ce-40df-a8ae-7ee932a38187.jpeg)
问题如图所示

**Comment by as7786971** [comment]
可以麻烦提供一下安卓11版本的demo吗？安卓不太熟悉，麻烦了，谢谢！

**Comment by tomjeans** [comment]
system.loadlibrary()那里打开路径的问题
