### ISSUE TITLE
OCRdemo无法运行

### ISSUE THREAD

**Issue by mengbai123** [PaddlePaddle/Paddle-Lite-Demo#348]
win10 AS版本2022.1.1Patch1 
都按照步骤下载完后  build完可以在build文件夹里面找到so文件  但是调试运行的apk里面没有
在gradle里面添加上
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
打包出来的有so文件了  但还是不能用  可以拍照但是不能标记出任何文字

**Comment by 1Q43** [comment]
It seems that you haven't downloaded the model to the specified directory.So the app won't do anything. 
Did you perform the following steps?
<img width="506" alt="pre" src="https://github.com/PaddlePaddle/Paddle-Lite-Demo/assets/22150849/e6985280-074e-4df2-9977-8fcd2e0f79d1">
