### ISSUE TITLE
怎么将模型转换成适应 andrid端的 nb文件

### ISSUE THREAD

**Issue by greadking** [PaddlePaddle/Paddle-Lite-Demo#351]

**Comment by rover12421** [comment]
[/Sources/github.com/PaddlePaddle/Paddle-Lite-Demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/ocr/android/shell/ppocr_demo#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E9%A2%84%E6%B5%8B%E5%BA%93)

如何更新预测库有说
