### ISSUE TITLE
iOS 平台出现崩溃

### ISSUE THREAD

**Issue by HEXUANDSDDFSD** [PaddlePaddle/Paddle-Lite-Demo#353]
<img width="1059" alt="截屏2023-04-12 17 25 27" src="https://user-images.githubusercontent.com/21185598/231415777-15257954-7f61-46b7-88d9-69ce79f596ec.png">

**Comment by hbulixu** [comment]
遇到相同问题，如何解决？

**Comment by lhyos** [comment]
严重问题1、      iOS 静态图识别准确，但是内存不释放，每次增加500M，3次崩溃
严重问题2、     iOS动态视频识别，识别框向右下方偏移
