### ISSUE TITLE
ppoce error

### ISSUE THREAD

**Issue by ZhaoMonica** [PaddlePaddle/Paddle-Lite-Demo#355]
andriod 
E/IPCThreadState: attemptIncStrongHandle(84): Not supported

**Comment by ZhaoMonica** [comment]
04/19 18:10:02: Launching 'app' on OPPO PEEM00.
Install successfully finished in 134 ms.
$ adb shell am start -n "com.baidu.paddle.lite.demo.object_detection/com.baidu.paddle.lite.demo.ppocr_demo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER


Print the above information and immediately return

**Comment by ZhaoMonica** [comment]
5.621 ...c/Paddle-Lite/lite/core/model/base/io.cc:46 BinaryFileReader] Check failed: file_: Unable to open file: /storage/emulated/0/Android/data/com.baidu.paddle.lite.demo.object_detection/files/models/ch_ppocr_mobile_v2.0_cls_slim_opt.nb
E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F  4/19 18:29: 5.621 ...c/Paddle-Lite/lite/core/model/base/io.cc:46 BinaryFileReader] Check failed: file_: Unable to open file: /storage/emulated/0/Android/data/com.baidu.paddle.lite.demo.object_detection/files/models/ch_ppocr_mobile_v2.0_cls_slim_opt.nb
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28698 (bject_detection), pid 28698 (bject_detection)

**Comment by 1Q43** [comment]
It seems that you haven't downloaded the model to the specified directory.Did you perform the following steps?

<img width="506" alt="pre" src="https://github.com/PaddlePaddle/Paddle-Lite-Demo/assets/22150849/550235c6-d250-4e0f-9712-67b5665f7f7b">
