### ISSUE TITLE
android demo只能框出文字，没有展示具体提取的文字，有对应的api么

### ISSUE THREAD

**Issue by cornflower10** [PaddlePaddle/Paddle-Lite-Demo#356]
android demo只能框出文字，没有展示具体提取的文字，有对应的api么

**Comment by cornflower10** [comment]
![image](https://user-images.githubusercontent.com/8315609/233932874-fcb9577b-b4c7-49ac-9d72-d12655202931.png)

**Comment by cornflower10** [comment]
![image](https://user-images.githubusercontent.com/8315609/233932981-35d3d9e8-7d68-4b32-a293-8f4ff9ae9fb2.png)

**Comment by cornflower10** [comment]
![image](https://user-images.githubusercontent.com/8315609/233933675-cad0371d-9332-4d63-907f-1cf01305ef10.png)

**Comment by szaboz** [comment]
Apparently, issues like this are caused if the .cpp files use incorrect image shapes with the models. I'm currently investigating this problem, my suspicion is that maybe the image shape configurations were not updated at one point when the models were.

**Comment by channingkuo** [comment]
修改pipeline.cc文件的这边即可，大概在309行，但是中文字使用openCV的putText方式是乱码
`
  predictTime = GetElapsedTime(t);

  // visualization
  auto img_res = Visualization(bgrImage_resize, boxes, savedImagePath);
  cv::Mat img_vis;
  cv::resize(img_res, img_vis, cv::Size(textureWidth, textureHeight));
  cv::cvtColor(img_vis, img_vis, cv::COLOR_BGR2RGBA);
  // show ocr results on image
  VisualizeResults(rec_text, rec_text_score, &img_vis,&visualizeResultsTime);
//  VisualizeStatus(readGLFBOTime, writeGLTextureTime, predictTime, rec_text,
//                  rec_text_score, visualizeResultsTime, &img_vis);
`
