### ISSUE TITLE
【A311D 跑官方Demo报错 corrupted size vs. prev_size， Aborted】

### ISSUE THREAD

**Issue by Taichipeace** [PaddlePaddle/Paddle-Lite-Demo#357]
【硬件】： 荣品A311D，ARM CPU， 4G内存
【系统平台】: Linux x64(Ubuntu 18.04)
【编译语言】： C++
整个过程完全按照 “OOCR 文字识别 Demo 使用指南” 操作的： https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/ocr/armlinux/shell/cxx/ppocr_demo

报错如下：
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1118 Setup] ARM multiprocessors name: HARDWARE        : AMLOGIC

[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1119 Setup] ARM multiprocessors number: 6
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 0, max freq: 2208, min freq: 2208, cluster ID: 1, CPU ARCH: A53
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 1, max freq: 2208, min freq: 2208, cluster ID: 1, CPU ARCH: A53
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 2, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 3, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 4, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 5, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1127 Setup] L1 DataCache size is:
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1131 Setup] L2 Cache size is:
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1135 Setup] L3 Cache size is:
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  5/ 3 11: 7:29.613 ...0rc/Paddle-Lite/lite/core/device_info.cc:1139 Setup] Total memory: 3839260KB
corrupted size vs. prev_size
Aborted

**Comment by Taichipeace** [comment]
Merci beaucoup de Master XY！

**Comment by rogerg6** [comment]
老哥，你后来怎么解决的
