### ISSUE TITLE
编译yolov5n-detection-demo, 报错

### ISSUE THREAD

**Issue by w1025773984** [PaddlePaddle/Paddle-Lite-Demo#365]

**Comment by w1025773984** [comment]
/home/simon/AndroidStudioProjects/Paddle-Lite-Demo-develop/object_detection/android/app/cxx/yolov5n_detection_demo/app/src/main/cpp/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /home/simon/AndroidStudioProjects/Paddle-Lite-Demo-develop/object_detection/android/app/cxx/yolov5n_detection_demo/app/src/main/cpp/CMakeLists.txt:18 (find_package):
  Found package configuration file:

    /home/simon/AndroidStudioProjects/Paddle-Lite-Demo-develop/object_detection/android/app/cxx/yolov5n_detection_demo/app/src/main/cpp/../../../OpenCV/sdk/native/jni/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

**Comment by 1Q43** [comment]
Perhaps you need to check if the file : OpenCV/sdk/native/jni/armeabi-v7a/OpenCVConfig.cmake exists.

OpenCV/sdk/native/jni/OpenCVConfig.cmake will check the corresponding OpenCVConfig.cmake file based on the abiFilters.From the log information, it appears that you are using armeabi-v7a.
