### ISSUE TITLE
OCR android ppocr_demo编译安装后黑屏

### ISSUE THREAD

**Issue by balcklive** [PaddlePaddle/Paddle-Lite-Demo#367]
软件可以正常编译安装和打开，但是一直黑屏，无法读取摄像头数据

其他问题：无法自动下载OpenCV库，手动下载并解压到ppocr_demo/app目录下之后才能继续编译

Android Gradle Plugin Version: 7.1.2

Gradle Version: 7.2

Opencv: 4.2 

Paddlite: 2.10

**Comment by 1Q43** [comment]
Did you perform the following steps?
![image](https://github.com/PaddlePaddle/Paddle-Lite-Demo/assets/22150849/95fc1e6c-491a-48fa-89e1-662ff7394609)

**Comment by szaboz** [comment]
Hi, similar problem here. I did all the steps, but for some reason neither the PaddleLite nor the OpenCV folders got created in the app directory. Even after debugging everything, checking the SDK Tools, setting the NDK version, etc. I still get a 'No variants found for ':app'. Check build files to ensure at least one variant exists. at: com.android.tools.idea.gradle.project.sync.AndroidModule.prepare(GradleModules.kt:266)' error when trying to build the project.

**Comment by szaboz** [comment]
Update: I completely reseted the project back to the git commit and manually added the two libraries and the NDK version. The build was now successful. I encountered the black screen bug after the first launch, but after I gave access to my camera and restarted the app it started to function seemingly right.
