### ISSUE TITLE
building failed, ld error

### ISSUE THREAD

**Issue by ClydeU420** [PaddlePaddle/Paddle-Lite-Demo#368]
ld: error: found local symbol '__bss_start__' in global part of symbol table in file 

there were six other local symble ld error occured

**Comment by ClydeU420** [comment]
is was happened when I build ppocr_demo app

**Comment by ClydeU420** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libNative.so" not found

**Comment by safehumeng** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libNative.so" not found
the same error
