### ISSUE TITLE
请问有ocr mac arm 环境下使用metal 或者opencl的例子吗 

### ISSUE THREAD

**Issue by kwdchol** [PaddlePaddle/Paddle-Lite-Demo#377]
目前看到的例子是mac ios环境下ocr 识别 我应该修改那部分让他运行在本机环境呢 或者
有ocr  mac arm 环境下使用metal 或者opencl的例子吗

**Comment by ddchenhao66** [comment]
您好，Demo仓库目前只支持Android、iOS 和 ArmLinux 三个平台。Mac环境在Metal后端的编译部署可以参考https://www.paddlepaddle.org.cn/lite/v2.12/source_compile/macos_compile_macos.html  和https://www.paddlepaddle.org.cn/lite/v2.12/demo_guides/metal.html。
