### ISSUE TITLE
resnet34训练后量化处理过的模型比原始模型速度更慢

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/Paddle-Lite-Demo#38]
线程：1
性能模式：LITE_POWER_HIGH
时间：800ms  -> 3400ms

**Comment by AIpioneer** [comment]
Hi， sorry for replying you late, if you still have any question in Quant, please raise your issue https://github.com/PaddlePaddle/PaddleSlim/issues here. Thanks
