### ISSUE TITLE
Android应用口罩识别业务模型集成问题

### ISSUE THREAD

**Issue by usherjc** [PaddlePaddle/Paddle-Lite-Demo#42]
### Android应用口罩识别业务模型集成问题

> 前言

本仓库中的android demo已成功下载并且在手机上正常运行。
手机型号 - 小米MIX2S
安卓系统 - Lineage os Android 9

> 问题

目前接到需求，在android工程里集成口罩识别业务。将Paddle-Lite-Demo仓库中的android工程下载后，成功在android studio中编译运行在手机上。而后观察项目结构：

1. 在app module下的build.gradle文件中有两段下载的业务代码，个人分析，是将下载地址中的Paddle-Lite的引擎与业务算法的nb文件下载至cache文件夹中；
2. 参照官网的[Java使用文档说明](https://paddlepaddle.github.io/Paddle-Lite/v2.2.0/java_api_doc/)，可以得知，PaddlePredictor起到初始化作用，模仿demo中的工程文件结构进行修改，将app module下的build.gradle的下载地址修改为 https://paddle-inference-dist.bj.bcebos.com/mask_detection.tar.gz ，这是[口罩识别C++Demo](https://github.com/PaddlePaddle/Paddle-Lite/tree/develop/lite/demo/cxx)中列出的口罩识别模型的下载地址，同时将cache文件夹、assets/model文件夹中的内容删除；
3. 以上工作完成后，点击android studio中的同步，项目正常编译完成，点击运行，可正常安装至手机上，但app立马闪退，编译器中无应用层日志输出。逐行调试代码，发现发生闪退处在PaddlePredictor.createPaddlePredictor(config)，此为引擎初始化的操作；

> 推测

观察原face_detection_demo工程的assets目录，如下图所示：
![image.png](https://upload-images.jianshu.io/upload_images/11481388-80b2f1893b443cf8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

修改后的mask_detection_demo工程的assets目录，如下图所示：
![image.png](https://upload-images.jianshu.io/upload_images/11481388-259d96b86f8071d3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

可以看到区别，口罩的工程里，model文件夹里面有两个目录，Paddle-Lite的开发人员告诉我说，口罩识别模型由两个模型组成，即人脸识别+口罩分类，而仓库中的demo都只有一个独立模型，所以个人推测，直接进行修改，因为目录结构的问题会导致异常产生崩溃。

麻烦开发小哥看一下是不是我推测这样。

**Comment by chenjiaoAngel** [comment]
![image](https://user-images.githubusercontent.com/38650344/75133398-942b0b00-5715-11ea-80a7-8b42745c93d4.png)
这个是有多个模型的目录存放形式，需要先确定以下几个问题：
1 assets拷贝文件时，有把这两个模型copy到手机目录下吗
2 加载模型的路径是否正确
我这边看不到你的截图，只能先这样给你意见。如果有问题，请及时反馈

**Comment by chenjiaoAngel** [comment]
可以参考image_classify_demo（https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/image_classification_demo），多个模型存放与选取

**Comment by usherjc** [comment]
> ![image](https://user-images.githubusercontent.com/38650344/75133398-942b0b00-5715-11ea-80a7-8b42745c93d4.png)
> 这个是有多个模型的目录存放形式，需要先确定以下几个问题：
> 1 assets拷贝文件时，有把这两个模型copy到手机目录下吗
> 2 加载模型的路径是否正确
> 我这边看不到你的截图，只能先这样给你意见。如果有问题，请及时反馈

已经成功集成运行

**Comment by chenjiaoAngel** [comment]
好，👍。
没问题话，辛苦关下issue

**Comment by xsbrsg** [comment]
你好，我也是遇到了同样的问题，运行到paddlePredictor = PaddlePredictor.createPaddlePredictor(config);这一行的时候闪退，日志报错如下：
![image](https://user-images.githubusercontent.com/61486634/76377799-cf207600-6386-11ea-88ed-298546832246.png)请问您是怎么解决的

**Comment by usherjc** [comment]
> 你好，我也是遇到了同样的问题，运行到paddlePredictor = PaddlePredictor.createPaddlePredictor(config);这一行的时候闪退，日志报错如下：
> ![image](https://user-images.githubusercontent.com/61486634/76377799-cf207600-6386-11ea-88ed-298546832246.png)请问您是怎么解决的

对着demo代码重写的。

**Comment by xsbrsg** [comment]
@usherjc 请问一下您预处理部分是怎么做的。我把模型放到java demo中，预处理部分参考的Android demo中的image_classification_demo项目，人脸检测的结果很不准确

**Comment by wk37** [comment]
大佬能上个demo吗？

**Comment by usherjc** [comment]
> @usherjc 请问一下您预处理部分是怎么做的。我把模型放到java demo中，预处理部分参考的Android demo中的image_classification_demo项目，人脸检测的结果很不准确

用最新的l引擎库试试看。

**Comment by usherjc** [comment]
> 大佬能上个demo吗？

您可以尝试一下将官方的demo改造一下。
