### ISSUE TITLE
求告知demo里所用到的PaddlePaddle源码

### ISSUE THREAD

**Issue by hang245141253** [PaddlePaddle/Paddle-Lite-Demo#43]
树莓派demo里的目标识别，之前用PaddleCV/SSD的源码运行出的模型替换demo的模型会识别错乱

![result](https://user-images.githubusercontent.com/44885245/75155292-af643d80-574a-11ea-8480-89a7da3577b9.jpg)

所以想要一份这个demo的PaddlePaddle源码，然后去学习一下如何从PaddlePaddle到PaddPaddlelite完整的部署一套自己的项目

**Comment by zhupengyang** [comment]
paddlepaddle: https://github.com/PaddlePaddle/Paddle 
paddlelite: https://github.com/PaddlePaddle/Paddle-Lite 
---
最好先用paddle跑一些图片，看下结果是否正确（保证模型的正确），然后再看是不是部署过程有问题

**Comment by hang245141253** [comment]
> ## paddlepaddle：[https](https://github.com/PaddlePaddle/Paddle)
> : //github.com/PaddlePaddle/Paddle paddlelite：[https](https://github.com/PaddlePaddle/Paddle) : [//github.com/PaddlePaddle/Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite)
> 最好先用paddle跑一些图片，看下结果是否正确（保证模型的正确），然后再看是不是部署过程有问题

在PaddlePaddle上跑过 ，用的PaddleCV/SSD跑的，原图片在PaddlePaddle上预测结果都正确没有问题。部署过程也没有问题，之前挂过issue。也在lite的群里询问过，有位lite的同学说可能是预处理出了问题，但具体啥问题也不知道在哪。一直卡在这里

**Comment by zhupengyang** [comment]
https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor.java 
195行开始的预处理需要自己改下，可能和ssd模型的预处理过程不一样

**Comment by hang245141253** [comment]
> [https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor。 java](https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor.java)
> 195行开始的预需要自己改下，可能和ssd模型的预过程不一样

谢谢老哥的提示 但是我这个用的是armlinux C++的demo啊  老哥能否帮忙指出一下C++源码需要修改的位置嘛

**Comment by zhupengyang** [comment]
> > [https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor。 java](https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/image_classification_demo/app/src/main/java/com/baidu/paddle/lite/demo/image_classification/Predictor.java)
> > 195行开始的预需要自己改下，可能和ssd模型的预过程不一样
> 
> 谢谢老哥的提示 但是我这个用的是armlinux C++的demo啊 老哥能否帮忙指出一下C++源码需要修改的位置嘛

https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc 65行开始的preprocess函数
