### ISSUE TITLE
Android端集成口罩检测模型有问题

### ISSUE THREAD

**Issue by xsbrsg** [PaddlePaddle/Paddle-Lite-Demo#46]
参考的是给出的[https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo](url)这个目标检测的例子。按照C++ demo中说的方法对模型进行转换，口罩检测的两个模型转换均没有报错，如图
![2](https://user-images.githubusercontent.com/61486634/76499866-7af6be00-647a-11ea-8629-86ef952111e3.png)。用pyramidbox_lite_opt.nb模型替换原来目标检测demo中的模型，运行app发现输出结果
![3](https://user-images.githubusercontent.com/61486634/76500208-18ea8880-647b-11ea-87bf-27743c68f791.png)
麻烦问一下为什么输出为空，是否和预处理有关，谢谢！

**Comment by wk37** [comment]
同求口罩检测android demo

**Comment by hong19860320** [comment]
口罩检测demo已经上传了 请访问https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/mask_detection_demo
