### ISSUE TITLE
mobilenet模型转换后嵌入image_classification_demo运行失常

### ISSUE THREAD

**Issue by sharon-gu** [PaddlePaddle/Paddle-Lite-Demo#47]
你好 我用paddlehub迁移模型mobilenet后再用opt工具转成naive_buffer格式，将转后的best_model.nb和对应的标签文件替换到paddlelite image_classification_demo apk,安装到手机预测结果错误。。 请大神指导一下
我的步骤：
1.cd PaddleHub/demo/image_classification
2../run_classifier.sh --module=mobilenet --checkpoint_dir=./checkpoint  --use_gpu=0
3./run_predict.sh --module=mobilenet --checkpoint_dir=./checkpoint  --use_gpu=0，预测自下载玫瑰图片为玫瑰，正常。
4../../../Paddle-Lite/opt --model_dir=./checkpoint/best_model \
      --valid_targets=arm \
      --optimize_out_type=naive_buffer \
      --optimize_out=/share/models/best_model

lable:~/.paddlehub/dataset/flower_photos/label_list.txt
5.替换paddlelite image_classification_demo的model.nb和标签文件，生成apk.
6.apk安装在arm8手机，预测自下载玫瑰图片为蒲公英，apk安装在arm7板，预测自下载玫瑰图片为郁金香。 异常。预测结果不对并且同一个apk同一图片在不同机型预测结果不一致！

**Comment by jiweibo** [comment]
可以尝试使用一下armv7版本，在手机上测试，看是否因因为arm版本的问题

**Comment by sharon-gu** [comment]
疑似opt的问题，issue提至paddle-lite repo.
close.
Thanks.
