### ISSUE TITLE
andriod集成口罩，app闪退

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/Paddle-Lite-Demo#54]
荣耀20手机 型号YAL-AL00  android 10  Magic UI 3.0.0
android studio 3.4.1
04/06 12:30:46: Launching app
$ adb install-multiple -r -t /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_8.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_2.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_3.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_1.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/dep/dependencies.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_0.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_5.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_4.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/resources/instant-run/debug/resources-debug.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_9.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_6.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_7.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/instant-run-apk/debug/app-debug.apk 
Split APKs installed in 10 s 897 ms
$ adb shell am start -n "com.baidu.paddle.lite.demo.mask_detection/com.baidu.paddle.lite.demo.mask_detection.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 16975 on device huawei-yal_al00-STSDU19529011335
Application terminated.

app run后

手机上mask detection小图标，点击打开，闪退（打不开）？？怎么解？

**Comment by xiaomujiang** [comment]
附加报错内容：
04/06 13:05:09: Launching app
$ adb install-multiple -r -t /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_8.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_2.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_3.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_1.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/dep/dependencies.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_0.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_5.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_4.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/resources/instant-run/debug/resources-debug.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_9.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_6.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/split-apk/debug/slices/slice_7.apk /home/zhangshilin/Paddle-Lite-Demo-master/PaddleLite-android-demo/mask_detection_demo/app/build/intermediates/instant-run-apk/debug/app-debug.apk 
Split APKs installed in 8 s 60 ms
$ adb shell am start -n "com.baidu.paddle.lite.demo.mask_detection/com.baidu.paddle.lite.demo.mask_detection.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 23057 on device huawei-yal_al00-STSDU19529011335
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/.mask_detectio: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10259(com.baidu.paddle.lite.demo.mask_detection) identical 10 lines
W/.mask_detectio: JIT profile information will not be recorded: profile file does not exits.
I/.mask_detectio: QarthPatchMonintor::Init
    QarthPatchMonintor::StartWatch
    QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
    QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.baidu.paddle.lite.demo.mask_detection
    QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
    QarthPatchMonintor::Run
I/.mask_detectio: QarthPatchMonintor::Reading
    QarthPatchMonintor::CheckNotifyEvent
    QarthPatchMonintor::CheckNotifyEvent before read
I/InstantRun: starting instant run server: is main process
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.mask_detection#10259#256
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.mask_detection#10259#0
D/OpenGLRenderer: disableOutlineDraw is true
I/AwareBitmapCacher: init processName:com.baidu.paddle.lite.demo.mask_detection pid=23057 uid=10259
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@cdebc7f
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@17f244c
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
I/QarthLog: [PatchStore] create disable file for com.baidu.paddle.lite.demo.mask_detection uid is 10259
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.mask_detection, PID: 23057
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.baidu.paddle.lite.demo.mask_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.mask_detection.MainActivity.<init>(MainActivity.java:41)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1257)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3663)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process: Sending signal. PID: 23057 SIG: 9
Application terminated.

**Comment by hong19860320** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found

按照这个方法看下能不能解决https://stackoverflow.com/questions/59794824/android-app-crash-after-ndk-upgraded-from-20-1-to-21-0

**Comment by hong19860320** [comment]
已经去掉了openmp的依赖，请拉最新代码试试。

**Comment by xiaomujiang** [comment]
拉取最新的，可以了

**Comment by hong19860320** [comment]
> 拉取最新的，可以了

嗯嗯，好的，麻烦关掉这个issue哈
