### ISSUE TITLE
什么时候出armlinux的python demo？

### ISSUE THREAD

**Issue by peterlhj** [PaddlePaddle/Paddle-Lite-Demo#56]
什么时候出armlinux的python demo？

**Comment by AIpioneer** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/315730  您好，可以先参考外部热心用户贡献的demo，后续我们会在官方也给出相应的demo

**Comment by peterlhj** [comment]
谢谢！这个也是c++版本的
