### ISSUE TITLE
human_segmentation_demo 更换模型文件model.nb后无法正常使用

### ISSUE THREAD

**Issue by lesterhnu** [PaddlePaddle/Paddle-Lite-Demo#66]
使用opt工具转换了人像分割模型，替换demo中的model.nb之后无法启动，会闪退，机型小米8和一加6都试过
错误信息为
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 23429 (Predictor Worke), pid 23399 (an_segmentation)
![image](https://user-images.githubusercontent.com/42615458/82723349-ea055400-9d00-11ea-89d3-4c08ba12358a.png)

opt 版本2.3.0和2.6.0都试过
（模型地址：https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_lite_inference.zip）

**Comment by lesterhnu** [comment]
这个项目是没人维护了么

**Comment by hong19860320** [comment]
替换前demo能运行吗？模型和paddlelite的库都替换了吗？

**Comment by lesterhnu** [comment]
> 替换前demo能运行吗？模型和paddlelite的库都替换了吗？

替换前可以运行，使用opt2.3和opt2.6的opt都转化过，预测库也都替换掉了也是不行，另外，我在使用opt转化的时候会出现这个错误
![image](https://user-images.githubusercontent.com/42615458/82852124-94b18880-9f34-11ea-88a3-715fccfa1b8c.png)

**Comment by InternetMaster1** [comment]
@lesterhnu @hong19860320  

Were you able to solve this issue?

I am facing similar problem trying to run humanseg_mobile on Android demo..

I posted an issue https://github.com/PaddlePaddle/PaddleSeg/issues/279#issuecomment-637364074

The advice by @Channingss  is this

> you can develop base on this demo, you need change .nb model, and custom preprocess and postprocess:
> https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/human_segmentation_demo

But I am unable to solve it yet. Any tips?

**Comment by zhupengyang** [comment]
The data type of out tensor of the human_segmentation_demo model  is int64. Java API does not support int64 yet. It will be fix in the next version of paddlelite.

**Comment by InternetMaster1** [comment]
Dear @zhupengyang 

In this issue https://github.com/PaddlePaddle/PaddleSeg/issues/279#issuecomment-638158456, @Channingss has advised to do image normalisation to make it work using following formula

> rgb[channelIdx[0]] - mean / std

Will that solve the int64 problem? I am struggling to make it work...

**Comment by InternetMaster1** [comment]
@zhupengyang 

Any help you could provide in making humanseg_mobile run on Android would be much appreciated. 

Thanks!

**Comment by zhupengyang** [comment]
- The demo is in update. #75 
- If your demo crashed, please update your ".nb" model and so to v2.6.1
- If your demo's result is wrong, please refer to [PR3750](https://github.com/PaddlePaddle/Paddle-Lite/pull/3750) to update your so.
@InternetMaster1  @lesterhnu

**Comment by InternetMaster1** [comment]
@zhupengyang 

Wow thanks a ton. Let me check this, and I will get back to you

**Comment by InternetMaster1** [comment]
@zhupengyang 

1) I am currently stuck at this crash
```
2020-06-05 20:28:43.643 21610-21628/com.baidu.paddle.lite.demo.human_segmentation E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.human_segmentation, PID: 21610
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=1487414144
        at com.baidu.paddle.lite.demo.segmentation.visual.Visualize.draw(Visualize.java:29)
        at com.baidu.paddle.lite.demo.segmentation.Predictor.runModel(Predictor.java:222)
        at com.baidu.paddle.lite.demo.segmentation.MainActivity.onRunModel(MainActivity.java:149)
        at com.baidu.paddle.lite.demo.segmentation.MainActivity$2.handleMessage(MainActivity.java:122)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
``` 
Debug Output: 
> We are getting  486796525568 at index location of colormap[] Array. It should be 0 or 1 as we used two color but we are getting value 486796525568.

2) To solve the above error, I have to make a new "so" file after pulling code in this [PR3750 ](https://github.com/PaddlePaddle/Paddle-Lite/pull/3750)? If yes, which guide to follow to create a new ".so" file? Is it [this document](https://github.com/PaddlePaddle/Paddle-Lite/blob/3bc6a928f5338e29e28f000a1baf379a298c8b76/docs/demo_guides/java_demo.md)?

**Comment by InternetMaster1** [comment]
These are the steps that I have completed till now

1. We cloned base project from below repository. 
https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/human_segmentation_demo

2. We changed paddleLiteLibs from 
https://paddlelite-demo.bj.bcebos.com/libs/android/paddle_lite_libs_v2_3_0.tar.gz
To 
https://paddlelite-demo.bj.bcebos.com/models/deeplab_mobilenet_fp32_for_cpu_v2_6_1.tar.gz

3. We changed paddleLiteModels from 
https://paddlelite-demo.bj.bcebos.com/models/deeplab_mobilenet_fp32_for_cpu_v2_3_0.tar.gz
To 
https://paddlelite-demo.bj.bcebos.com/models/deeplab_mobilenet_fp32_for_cpu_v2_6_1.tar.gz

4. We are not looking for Deeplab/MobileNet. We are looking for looking for a demo or Android code for "humanseg-mobile" based on HRNet "humanseg_mobile_quant". Thus, we  used the following command format to convert the "humanseg_mobile_quant" to "nb" file using the opt tool. 
paddlelite opt version:v2.6.1

```
> paddle_lite_opt \
>     --model_file=output/quant_offline/__model__ \
>     --param_file=output/quant_offline/__params__ \
>     --optimize_out_type=naive_buffer \
>     --optimize_out=nb_folder/Model_new \
>     --valid_targets=arm
```

I took reference from this link
https://paddle-lite.readthedocs.io/zh/latest/user_guides/opt/opt_python.html

5. Finally, I generated a model.nb file using opt version 2.6.1 from above command. 
I have put this above generated "model.nb file" in the assets folder 

6. In String.xml, I changed the input shape default value as below (since humanseg_mobile is based on 192,192 size)
<string name="INPUT_SHAPE_DEFAULT">1,3,192,192</string>

7. If we run project with  Paddlelite model deeplab_mobilenet_fp32_for_cpu_v2_6_1.tar.gz (model.nb), project is running properly and giving output properly. 

8. If we replace the above model with our converted Model (humanseg_mobile_quant.nb), and we changed
float[] output = outputTensor.getFloatData();
To 
long[] output = outputTensor.getLongData();

Then the application is getting Crash with the error mentioned in previous comment.

**Comment by InternetMaster1** [comment]
@ZeyuChen 

I recompiled and created a new "so" file after pulling code in this PR3750. Now I am getting this error

**Error**

> bad class file: C:\Users\Admin\Desktop\test\Paddle-Lite-Demo-master\PaddleLite-android-demo\human_segmentation_demo\app\libs\PaddlePredictor.jar(com/baidu/paddle/lite/MobileConfig.class)
>     class file has wrong version 55.0, should be 52.0
>     Please remove or make sure it appears in the correct subdirectory of the classpath.

**Steps Done**
1) Ran this command to recompile (based on pulled files of PR3750). Is this command correct?
```
./lite/tools/build.sh        \
    --arm_os=android         \
    --arm_abi=armv8          \
    --arm_lang=gcc           \
    --android_stl=c++_static \
    --build_extra=ON         \
    full_publish
```

2) Copied new generated PaddlePredictor.jar
From : build.lite.android.armv8.gcc\inference_lite_lib.android.armv8\java\jar
To     : Paddle-Lite-Demo-master\PaddleLite-android-demo\human_segmentation_demo\app

3) Copied generated libpaddle_lite_jni.so 
From : build.lite.android.armv8.gcc\inference_lite_lib.android.armv8\java\so 
To : Paddle-Lite-Demo-master\PaddleLite-android-demo\human_segmentation_demo\app\src\main\jniLibs\arm64-v8a


What else can I try? I have been trying to make this work since almost a week now and still I am unsuccessful.

Is it possible to get a ready Android demo of humanseg_mobile from the Paddle Team? This would be useful to the other users too...

**Comment by zhupengyang** [comment]
> based on HRNet "humanseg_mobile_quant"

@InternetMaster1 
Would you provide the paddle model (not .nb model) ?

**Comment by InternetMaster1** [comment]
Model File : https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip

Taken from https://github.com/PaddlePaddle/PaddleSeg/tree/release/v0.5.0/contrib/HumanSeg



Model type | Checkpoint | Inference Model | Quant Inference Model | Remarks
-- | -- | -- | -- | --
HumanSeg-mobile | humanseg_mobile_ckpt | humanseg_mobile_inference | [humanseg_mobile_quant](https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip) | Lightweight model, suitable for the front camera scene of the mobile or server CPU, the model structure is HRNet_w18_samll_v1, the input size (192, 192)

**Comment by InternetMaster1** [comment]
@zhupengyang 

> class file has wrong version 55.0, should be 52.0

To solve the above error, I recompiled by using Java 8 instead of Java 11, based on following chart

JVM | Major version
-- | --
Java 8 | 52
Java 9 | 53
Java 10 | 54
Java 11|55

But now I am getting a new error

> 2020-06-07 19:31:26.720 19640-19659/com.baidu.paddle.lite.demo.human_segmentation A/Paddle-Lite: [F  6/ 7 19:31:26.720 ...htdocs/Paddle-Lite/lite/api/light_api.cc:162 BuildRuntimeProgram] Check failed: it != kernels.end():
> -------- beginning of crash
> 2020-06-07 19:31:26.720 19640-19659/com.baidu.paddle.lite.demo.human_segmentation A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 19659 (Predictor Worke), pid 19640 (an_segmentation)

The struggle continues.... :-)

**Comment by zhupengyang** [comment]
> Model File : https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip

<img width="269" alt="image" src="https://user-images.githubusercontent.com/50474132/84010023-a8360800-a9a6-11ea-8957-ecb9360cd204.png">
Try to remove the unsqueeze2 op? It does not support int64_t now.

**Comment by InternetMaster1** [comment]
@zhupengyang 

I see that you added code for  Unsqueeze2 support. 
https://github.com/PaddlePaddle/Paddle-Lite/pull/3762/files

Thanks... I will try to compile using it and get back.

**Comment by zhupengyang** [comment]
> @zhupengyang
> 
> I see that you added code for Unsqueeze2 support.
> https://github.com/PaddlePaddle/Paddle-Lite/pull/3762/files
> 
> Thanks... I will try to compile using it and get back.
> 
> edit: I noticed that PR3762 is not yet merged into Develop branch. Should I take the code from PR3762 directly?

Maybe take the code from develop directly.  PR3762 is not for this issue.

**Comment by InternetMaster1** [comment]
1. I had taken from develop yesterday (around 24 hours ago) in which I had taken code from #PR3750 too. Has some more changes come into Develop branch related to my error?

2. If I do the above, then also I have to do the step to "remove the unsqueeze2 op"? I don't have any idea how to do that.

I will try again with directly "Develop" branch and get back to you...

**Comment by InternetMaster1** [comment]
> 4\. we  used the following command format to convert the "humanseg_mobile_quant" to "nb" file using the opt tool.
>     paddlelite opt version:v2.6.1
> 
> ```
> > paddle_lite_opt \
> >     --model_file=output/quant_offline/__model__ \
> >     --param_file=output/quant_offline/__params__ \
> >     --optimize_out_type=naive_buffer \
> >     --optimize_out=nb_folder/Model_new \
> >     --valid_targets=arm
> ```

Is my this step correct for creating "nb" file?

**Comment by InternetMaster1** [comment]
> 1. Ran this command to recompile (based on pulled files of PR3750). Is this command correct?
> 
> ```
> ./lite/tools/build.sh        \
>     --arm_os=android         \
>     --arm_abi=armv8          \
>     --arm_lang=gcc           \
>     --android_stl=c++_static \
>     --build_extra=ON         \
>     full_publish
> ```

Is this command also correct? Are all the values correctly? 

"c++static" & "ON"?

**Comment by InternetMaster1** [comment]
@zhupengyang 

> Maybe take the code from develop directly. PR3762 is not for this issue.

I again recompiled using the code in Develop branch, but I am getting the same error

> 2020-06-08 17:29:21.370 23171-23199/com.baidu.paddle.lite.demo.human_segmentation A/Paddle-Lite: [F  6/ 8 17:29:21.370 ...htdocs/Paddle-Lite/lite/api/light_api.cc:162 BuildRuntimeProgram] Check failed: it != kernels.end():  
>     --------- beginning of crash
> 2020-06-08 17:29:21.371 23171-23199/com.baidu.paddle.lite.demo.human_segmentation A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 23199 (Predictor Worke), pid 23171 (an_segmentation)

The above error comes when I use the model.nb that I generated using the [human_seg_quant](https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip) file.

Note: If I use the model.nb file from [Deeplab](https://paddlelite-demo.bj.bcebos.com/models/deeplab_mobilenet_fp32_for_cpu_v2_6_1.tar.gz) link, then it works. But we don't want deeplab, we want humanseg to work.

**Comment by InternetMaster1** [comment]
@zhupengyang 

Any tips on what I can try next?

**Comment by zhupengyang** [comment]
- checkout develop branch to compile the opt tool (not use opt-v2.6.1). [opt doc](https://paddle-lite.readthedocs.io/zh/latest/user_guides/model_optimize_tool.html)
- convert your model by the new opt
- checkout develop branch to compile the new so. 
```
./lite/tools/build_android.sh --with_extra=ON
```
- replace the model and so of this demo

@InternetMaster1

**Comment by InternetMaster1** [comment]
Ok let me check this and get back to you. 

Many thanks! 

@zhupengyang

**Comment by InternetMaster1** [comment]
@zhupengyang 

I was successfully able to compile opt, so and lib from the develop branch. But I am getting this error when I try to generate a model.nb file using the new opt tool

> [F 6/12 7:16:21. 1 ...lite/core/mir/static_kernel_pick_pass.cc:164 Apply] Check failed: !instruct.kernels().empty(): No kernels found for conv2d
Aborted (core dumped)


**Steps Followed :-**

**1. Compile OPT tool**
I compiled opt tool using the develop branch successfully
- Cloned
`https://github.com/PaddlePaddle/Paddle-Lite.git
`
- Command used
`./lite/tools/build.sh build_optimize_tool
`
- Version of opt
`opt version:b9f9a2d5
`

**2. Generate model.nb file**
Converting model using above opt tool is giving error

- We download and extracted the model file https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip
- Then we ran the following opt command
```
/www/htdocs/Paddle-Lite/build.opt/lite/api/opt 
--model_file=humanseg_mobile_quant/__model__ 
--param_file=humanseg_mobile_quant/__params__  
--optimize_out_type=naive_buffer 
--optimize_out=new-model 
--valid_targets=arm
```
- I am getting below **error**
> [F  6/12  7:16:21.  1 ...lite/core/mir/static_kernel_pick_pass.cc:164 Apply] Check failed: !instruct.kernels().empty(): No kernels found for conv2d
> Aborted (core dumped)

**Comment by InternetMaster1** [comment]
Dear @zhupengyang ,

Any tips on how to solve this error?

> [F 6/12 7:16:21. 1 ...lite/core/mir/static_kernel_pick_pass.cc:164 Apply] Check failed: !instruct.kernels().empty(): No kernels found for conv2d
Aborted (core dumped)

The steps are mentioned in the previous comment

**Comment by InternetMaster1** [comment]
Dear @zhupengyang ,

Any further help you could provide would be greatly appreciated.

:-)

**Comment by juncaipeng** [comment]
@InternetMaster1  Please use [v1.6.1 opt](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.6.1/opt) to optimize the quantized model.

**Comment by InternetMaster1** [comment]
@juncaipeng 

I had already tried (and I again tried) to compile the model.nb file using opt tool v2.6.1

It gives this error when I run using human segmentation demo

https://github.com/PaddlePaddle/Paddle-Lite-Demo/issues/66#issuecomment-639653146

**Comment by juncaipeng** [comment]
@InternetMaster1  

Please pull the latest code of develop branch. 

Run `./lite/tools/build.sh build_optimize_tool` to compile the opt.

I use the opt convert the [origin quantized model](https://paddleseg.bj.bcebos.com/humanseg/models/humanseg_mobile_quant.zip) successfully.

**Comment by xiaotianns** [comment]
@lesterhnu 我也是替换nb文件后，手机上app闪退，请问你解决了吗？然后还报了这些错误，能看一下吗，感激不尽
![image](https://user-images.githubusercontent.com/65651205/234845994-c9807b20-c05a-47a2-8eb7-6abfde0207b4.png)
