### ISSUE TITLE
seg部署到arm_inux移动端如何操作

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/Paddle-Lite-Demo#78]
PaddleLite-armlinux-demo只有检测和分类，我想在rk3399上进行分割任务，不知道如何下手，我已经完成训练-模型导出-模型转换，现在卡在lite部署，希望能给一定的建议；我见贵方在Android端有分割示例，不知道arm_linux端有类似示例吗

**Comment by hong19860320** [comment]
armlinux暂时没有示例，但是可以参考object_dection_demo修改下图像预处理和后处理的代码，特别需要提醒的是，先用Netron或VisualDL查看下paddle推理模型的输出输出的shape和数据类型，例如int64这样的类型，然后修改预处理的均值、方差并确认输入tensor的shape，最后，拿到输出tensor后，修改原demo中的后处理代码，将输出tensor的数据转为图像的mask，然后使用cv提供的方法merge原始图像和生成的mask即可。

**Comment by liangruofei** [comment]
收到，明白了，感谢指导




| |
梁若飞
邮箱：liangruofeinuc@163.com
|

签名由 网易邮箱大师 定制

在2020年06月16日 20:26，hong19860320 写道：

armlinux暂时没有示例，但是可以参考object_dection_demo修改下图像预处理和后处理的代码，特别需要提醒的是，先用Netron或VisualDL查看下paddle推理模型的输出输出的shape和数据类型，例如int64这样的类型，然后修改预处理的均值、方差并确认输入tensor的shape，最后，拿到输出tensor后，修改原demo中的后处理代码，将输出tensor的数据转为图像的mask，然后使用cv提供的方法merge原始图像和生成的mask即可。
