### ISSUE TITLE
FasterRCNN部署问题

### ISSUE THREAD

**Issue by edencfc** [PaddlePaddle/Paddle-Lite-Demo#82]
有的目标检测场景对时间要求稍微宽松，此时FasterRCNN预测效果比YoloV3好很多，目前还没有FasterRCNN的demo示例，如果要部署需要怎么做？

**Comment by AIpioneer** [comment]
这方面还是参考给的示例，自己来写啊  模型太多了，很难把所有的示例都提供出来

**Comment by edencfc** [comment]
好的，谢谢
