### ISSUE TITLE
在nanopc-t4上跑ssdlite_mobilenetv3_large遇到 segmentation fault 问题。

### ISSUE THREAD

**Issue by daiyuanm** [PaddlePaddle/Paddle-Lite-Demo#86]
我在服务器上用ssdlite_mobilenetv3_large训练了自己的数据集，然后在服务器上的评估，预测都是正常的。之后利用opt（2.3.0）工具将所得__model__和__params__文件转换成nb文件（全程未报错）。

之后想利用官方的pplite_demo中的目标检测部分来测试。更改了object_detection_demo.cc中的INPUT_SHAPE = {1, 3, 320, 320}; INPUT_MEAN= {0.485, 0.456, 0.406};INPUT_STD={0.229, 0.224, 0.225}。
然后执行run.sh，就出现Segmentation fault (core dumped)这个错误。
我看了之前的issue，里面有用yolov3部署的时候出现同样问题，说是yolov3要有两个输入。是否mobiletv3+ssdlite也是同样的问题？
又或者是我还需要对object_detection_demo.cc中调用的api进行更改？

**Comment by daiyuanm** [comment]
我用gdb调试，出现这样的信息。

![微信图片_20200820104028](https://user-images.githubusercontent.com/67545374/90710749-9b506180-e2d1-11ea-905b-87bebb04c4f8.jpg)

**Comment by hong19860320** [comment]
因为yolo模型确实需要两个输入，建议用将__model__文件拖入Netron https://lutzroeder.github.io/netron/ 看下输入是否是两个，如果是两个，则需要修改demo代码，增加一个输入。
