### ISSUE TITLE
口罩检测中，如何通过传入Bitmap得到预测结果

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle-Lite-Demo#89]
[mask_detection_demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/mask_detection_demo)

在该Demo中，我一直找不到传入Bitmap的入口，和获取预测结果的方法，请问如何得到这个。

**Comment by hong19860320** [comment]
已增加，请参考ssd_detection_demo https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/e9eae36bdd3e8278f5afd01e9a6ddbd4eba80b10/PaddleLite-android-demo/ssd_detection_demo/app/src/main/cpp/Native.cc#L78
