### ISSUE TITLE
PaddlePredictor.jar does not exist

### ISSUE THREAD

**Issue by zxj11838** [PaddlePaddle/Paddle-Lite-Demo#92]
When I run face_detection_demo, it appears as follows:
Transform output file E:\Androidproject\face\Paddle-Lite-Demo-master\PaddleLite-android-demo\face_detection_demo\app\libs\PaddlePredictor.jar does not exist.
Is this file automatically generated？？

**Comment by chao-er** [comment]
You can generate your own jar file under the guide of this webpage.  https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_andriod.html
