### ISSUE TITLE
fatal error: paddle_api.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by automano** [PaddlePaddle/Paddle-Lite-Demo#94]
环境：树莓派4 （已源码编译Paddle-Lite）

运行：
$ cd Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo
$ ./run.sh armv7hf 

有如下报错：

[ 50%] Building CXX object CMakeFiles/image_classification_demo.dir/image_classification_demo.cc.o
/home/pi/Documents/paddle/Paddle-Lite-Demo/PaddleLite-armlinux-demo/image_classification_demo/image_classification_demo.cc:15:10: fatal error: paddle_api.h: 没有那个文件或目录
 #include "paddle_api.h"
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/image_classification_demo.dir/build.make:63：CMakeFiles/image_classification_demo.dir/image_classification_demo.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/image_classification_demo.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
./run.sh:行19: ./image_classification_demo: 没有那个文件或目录

**Comment by chao-er** [comment]
运行demo前少了一步下载依赖库的过程，可以按照链接(https://paddle-lite.readthedocs.io/zh/latest/demo_guides/linux_arm_demo.html)中的指示，先下载对应依赖（对应帖子部署依赖步骤2）

**Comment by automano** [comment]
感谢感谢~！确实是。我蠢了。

**Comment by longshifeng** [comment]
@automano @cha0cha0 你好，
我也是树莓派编译 出现fatal error: paddle_api.h: 没有那个文件或目录 错误

但是我已经sh download.sh了 并且也已经 successful了
 
![image](https://user-images.githubusercontent.com/32770755/103476088-b2f63580-4ded-11eb-9794-c548b6f5b0bd.png)

这是为什么啊？？
