### ISSUE TITLE
yolo detection demo安卓部署

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/Paddle-Lite-Demo#99]
运行lite安卓yolo detection demo
成功在手机端安装上app，但是闪退，以下是安卓studio build的信息，未报错。
感觉应该是这里的问题，但是才接触astudio，不知道什么意思
ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI, ARMEABI_V7A' not targeted by this project.
ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI, ARMEABI_V7A' not targeted by this project.

build output 如下：
Executing tasks: [:app:assembleDebug] in project /home/hjs/Paddle-Lite-Demo/PaddleLite-android-demo/yolo_detection_demo

> Configure project :app
ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI, ARMEABI_V7A' not targeted by this project.
ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI, ARMEABI_V7A' not targeted by this project.

> Task :app:downloadAndExtractArchives
Downloading and extracting archives including libs and models

> Task :app:preBuild
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:generateJsonModelDebug UP-TO-DATE

> Task :app:externalNativeBuildDebug
Build Native arm64-v8a
ninja: no work to do.

> Task :app:compileDebugSources
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:mergeDexDebug UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithStripDebugSymbolForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
29 actionable tasks: 2 executed, 27 up-to-date

Build Analyzer results available

**Comment by cha0cha0** [comment]
看起来像是你修改了工程文件：Paddle-Lite-Demo/PaddleLite-android-demo/yolo_detection_demo/app/build.gradle
这里面的abiFilters原本只有'arm64-v8a'，看编译结果你这边多出了armeabi-v7a,armeabi
